openapi: 3.0.1
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2401.1.5**

    >

    > Date: **February 15, 2024**


    ---


    #### Available Documentation

    * [Postman](https://documenter.getpostman.com/view/224925/SzYgQufe)

    * [Open API](https://doc.mist-lab.fr/)


    ---


    #### Useful links

    * [Mist Homepage](https://www.mist.com)

    * [Mist Documentation](https://www.mist.com/documentation)

    * [Official API Documentation](https://api.mist.com/api/v1/docs/Home) (Mist account
    required)

    * [Mist Blog](https://www.mist.com/news/?md_post_type=post)

    * [Mist Updates](https://www.mist.com/documentation/category/product-updates/)'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist API
  version: 2401.1.5
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Europe 01
  url: https://api.eu.mist.com
- description: Mist APAC 01
  url: https://api.ac5.mist.com
security:
- apiToken: []
- basicAuth: []
tags:
- name: Webhook Samples
paths:
  /webhook_example/_alarm_:
    parameters: []
    post:
      description: 'Webhook sample for `alarm` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages'
      operationId: alarms
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - aps:
                    - string
                    bssids:
                    - string
                    count: 0
                    event_id: a7a26ff2-e851-45b6-9634-d595f45458b7
                    for_site: true
                    id: 489f6eca-6276-4993-bfeb-c3cbbbba1f08
                    last_seen: 0
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    ssids:
                    - string
                    timestamp: 0
                    type: string
                    update: true
                  topic: alarms
            schema:
              $ref: '#/components/schemas/webhook_alarms'
        description: "**N.B.**: Fields like `aps`, `bssids`, `ssids` are event specific.\
          \ They are relevant to this event type ( rogue-ap-detected). For a different\
          \ event type, different fields may be sent. These don\u2019t contain all\
          \ affected entities and are representative samples of entities (capped at\
          \ 10). For marvis action related events, we expose `details` to include\
          \ more event specific details.\n\nEvents specific fields for other alarm\
          \ event type can be found with API https://api.mist.com/api/v1/const/alarm_defs,\
          \ under \u201Cfields\u201D array of /alarm_defs response object."
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: alarms
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_asset_raw_:
    parameters: []
    post:
      description: 'Webhook sample for `asset_raw` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages


        **will be deprecated after 03/31/2024**'
      operationId: assetRaw
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - asset_id: b4695157-0d1d-4da0-8f9e-5c53149389e4
                    beam: 0
                    device_id: 3bafab7b-4400-4bcf-8e6e-09f954699940
                    ibeacon_major: 0
                    ibeacon_minor: 0
                    ibeacon_uuid: 1f89bc00-d0af-481b-82fe-a6629259a39f
                    mac: string
                    map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                    mfg_company_id: 0
                    mfg_data: string
                    rssi: 0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                  topic: asset-raw
            schema:
              $ref: '#/components/schemas/webhook_asset_raw'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: assetRaw
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_audit_:
    parameters: []
    post:
      description: 'Webhook sample for `audit` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages'
      operationId: audits
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  events:
                  - admin_name: admin_name8
                    device_id: 00000380-0000-0000-0000-000000000000
                    id: 0000122a-0000-0000-0000-000000000000
                    message: message0
                    org_id: 00001302-0000-0000-0000-000000000000
                    site_id: 00000290-0000-0000-0000-000000000000
                    src_ip: src_ip6
                    timestamp: 157.68
                  topic: audits
            schema:
              $ref: '#/components/schemas/webhook_audits'
        description: ''
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: audits
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_client_info_:
    parameters: []
    post:
      description: 'Webhook sample for `client_info` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: clientInfo
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    band: string
                    bssid: string
                    connect: 0
                    connect_float: 0
                    mac: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    rssi: 0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    ssid: string
                    timestamp: 0
                    version: 0
                    wlan_id: 5028e92b-fc59-4056-91d1-ea4b4ca1617a
                  topic: client-info
            schema:
              $ref: '#/components/schemas/webhook_client_info'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: clientJoin
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_client_join_:
    parameters: []
    post:
      description: 'Webhook sample for `client_join` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: clientJoin
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    band: string
                    bssid: string
                    connect: 0
                    connect_float: 0
                    mac: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    rssi: 0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    ssid: string
                    timestamp: 0
                    version: 0
                    wlan_id: 5028e92b-fc59-4056-91d1-ea4b4ca1617a
                  topic: client-join
            schema:
              $ref: '#/components/schemas/webhook_client_join'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: clientJoin
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_client_latency_:
    parameters: []
    post:
      description: 'Webhook sample for `client-latency` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages'
      operationId: client_latency
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  events:
                  - auth: 0.17170219
                    dhcp: 0.017828934
                    dns: 0.024532124
                    org_id: 2818e386-8dec-2562-9ede-5b8a0fbbdc71
                    site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                    timestamp: 1696401600
                  topic: client-latency
            schema:
              $ref: '#/components/schemas/webhook_client_latency'
        description: ''
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: alarms
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_client_sessions_:
    parameters: []
    post:
      description: 'Webhook sample for `client_sessions` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: clientSessions
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    band: string
                    bssid: string
                    client_family: string
                    client_manufacture: string
                    client_model: string
                    client_os: string
                    connect: 0
                    connect_float: 0
                    disconnect: 0
                    disconnect_float: 0
                    duration: 0
                    mac: string
                    next_ap: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    rssi: 0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    ssid: string
                    termination_reason: 0
                    timestamp: 0
                    version: 0
                    wlan_id: 5028e92b-fc59-4056-91d1-ea4b4ca1617a
                  topic: client-sessions
            schema:
              $ref: '#/components/schemas/webhook_client_sessions'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
      summary: clientSessions
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_device_events_:
    parameters: []
    post:
      description: 'Webhook sample for `device_events` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: deviceEvents
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    audit_id: 78c04fa6-cfb4-46a0-9aa5-3681ba4f3897
                    device_name: string
                    device_type: ap
                    ev_type: notice
                    mac: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    reason: string
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    text: string
                    timestamp: 0
                    type: string
                  topic: device-events
            schema:
              $ref: '#/components/schemas/webhook_device_events'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: deviceEvents
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_device_updowns_:
    parameters: []
    post:
      description: 'Webhook sample for `device_updowns` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: deviceUpDown
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    for_site: true
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    timestamp: 0
                    type: string
                  topic: device-updowns
            schema:
              $ref: '#/components/schemas/webhook_device_updowns'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: deviceUpDown
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_discovered_raw_rssi_:
    parameters: []
    post:
      description: 'Webhook sample for `discovered-raw-rssi` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: discovered-raw-rssi
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  events:
                  - ap_loc:
                    - 0
                    beam: 0
                    device_id: 3bafab7b-4400-4bcf-8e6e-09f954699940
                    ibeacon_major: 0
                    ibeacon_minor: 0
                    ibeacon_uuid: 1f89bc00-d0af-481b-82fe-a6629259a39f
                    is_asset: true
                    mac: string
                    map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                    mfg_company_id: string
                    mfg_data: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    rssi: 0
                    service_packets:
                    - service_data: string
                      service_uuid: 7138cc00-c611-4dec-a05e-5c4b1cae13c0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                  topic: string
            schema:
              $ref: '#/components/schemas/webhook_discovered_raw_rssi'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: discovered-raw-rssi
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_location_:
    parameters: []
    post:
      description: 'Webhook sample for `location` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: location
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - battery_voltage: 0
                    eddystone_uid_instance: string
                    eddystone_uid_namespace: string
                    eddystone_url_url: string
                    ibeacon_major: 0
                    ibeacon_minor: 0
                    ibeacon_uuid: 1f89bc00-d0af-481b-82fe-a6629259a39f
                    id: 487f6eca-6276-4993-bfeb-e3cbbbba3f08
                    mac: string
                    map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                    mfg_company_id: 0
                    mfg_data: string
                    name: string
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                    type: string
                    x: 0
                    y: 0
                  topic: location
            schema:
              $ref: '#/components/schemas/webhook_location'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: location
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_nac_accounting_:
    parameters: []
    post:
      description: 'Webhook sample for `nac-accounting` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: nacAccounting
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  events:
                  - ap: 5c5b355005be
                    auth_type: eap-tls
                    bssid: 5c5b35546bb4
                    client_ip: 172.16.87.4
                    client_type: wireless
                    mac: 6e795836d5f9
                    nas_vendor: juniper-mist
                    org_id: 625aba64-fe72-4b14-8985-cbf31ec3d78a
                    rx_pkts: 9523
                    site_id: ec9d1e85-af24-43f9-8d65-d620580e8631
                    ssid: Test-CMR SSID
                    timestamp: 1547235620.89
                    tx_pkts: 5233
                    type: NAC_ACCOUNTING_STOP
                    username: hi
                  topic: nac-accounting
            schema:
              $ref: '#/components/schemas/webhook_nac_accounting'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: nacAccounting
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_nac_events_:
    parameters: []
    post:
      description: Example Delivery of nac-events
      operationId: nac-events
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  events:
                  - ap: 5c5b35513227
                    auth_type: 802.1X
                    bssid: 5c5b355fafcc
                    dryrun_nacrule_id: 32f27e7d-ff26-4a9b-b3d1-ff9bcb264012
                    dryrun_nacrule_matched: true
                    idp_id: 912ef72e-2239-4996-b81e-469e87a27cd6
                    idp_role:
                    - itsuperusers
                    - vip
                    mac: ac3eb179e535
                    nacrule_id: 32f27e7d-ff26-4a9b-b3d1-ff9bcb264c62
                    nacrule_matched: true
                    nas_vendor: juniper-mist
                    org_id: 27547ac2-d114-4e04-beb1-f3f1e6e81ec6
                    random_mac: true
                    resp_attrs:
                    - Tunnel-Type=VLAN
                    - Tunnel-Medium-Type=IEEE-802
                    - Tunnel-Private-Group-Id=750
                    - User-Name=anonymous
                    site_id: 441a1214-6928-442a-8e92-e1d34b8ec6a6
                    ssid: '##mist_nac'
                    timestamp: 1691512031.358188
                    type: NAC_CLIENT_PERMIT
                    username: user@deaflyz.net
                    vlan: '750'
                  topic: string
            schema:
              $ref: '#/components/schemas/webhook_nac_events'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: nac-events
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_occupancy_alerts_:
    parameters: []
    post:
      description: 'Webhook sample for `occupancy_alerts` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: occupancyAlerts
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - alert_events:
                    - current_occupancy: 0
                      map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                      occupancy_limit: 0
                      org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                      timestamp: 0
                      type: COMPLIANCE-VIOLATION
                      zone_id: 4495020a-236f-46e0-9453-e3f9cc6476f4
                      zone_name: string
                    for_site: true
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                  topic: occupancy-alerts
            schema:
              $ref: '#/components/schemas/webhook_occupancy_alerts'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: occupancyAlerts
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_ping_:
    parameters: []
    post:
      description: 'Webhook sample for `ping` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: ping
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - id: 487f6eca-6276-4993-bfeb-f3cbbbba4f08
                    name: string
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                  topic: ping
            schema:
              $ref: '#/components/schemas/webhook_ping'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: ping
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_sdkclient_scan_data:
    parameters: []
    post:
      description: 'Webhook sample for `sdkclient_scan_data` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: sdkclientScanData
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - connection_ap: 5c5b352f587e
                    connection_band: '2.4'
                    connection_bssid: 5c5b352b51b4
                    connection_channel: 11
                    connection_rssi: -87
                    last_seen: 1592333828
                    mac: 70ef0071535f
                    scan_data:
                    - ap: 5c5b352f587e
                      band: '2.4'
                      bssid: 5c5b352b51b4
                      channel: 11
                      rssi: -87
                      ssid: mist-wifi
                      timestamp: 1592333828
                    - ap: 5c5b352f587e
                      band: '5'
                      bssid: 5c5b352b51b8
                      channel: 36
                      rssi: -75
                      ssid: mist-wifi
                      timestamp: 1592333828
                    site_id: d761985e-49b1-4506-88e9-e0368a05c301
                  topic: sdkclient-scan-data
            schema:
              $ref: '#/components/schemas/webhook_sdkclient-scan-data'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: sdkclientScanData
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_site_sle_:
    parameters: []
    post:
      description: 'Webhook sample for `site-sle` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages'
      operationId: site-sle
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  events:
                  - org_id: 2818e386-8dec-2562-9ede-5b8a0fbbdc71
                    site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                    sle:
                      ap-availability: 0.6
                      successful-connect: 0.7
                      time-to-connect: 0.9
                    timestamp: 1694620800
                  topic: site-sle
            schema:
              $ref: '#/components/schemas/webhook_site_sle'
        description: ''
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: site-sle
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
  /webhook_example/_zone_:
    parameters: []
    post:
      description: 'Webhook sample for `zone` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: zone
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - asset_id: b4695157-0d1d-4da0-8f9e-5c53149389e4
                    id: 485f6eca-6276-4993-bfeb-54cbbbba5f08
                    mac: string
                    map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                    name: string
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                    trigger: enter
                    type: string
                    zone_id: 4495020a-236f-46e0-9453-e3f9cc6476f4
                  topic: zone
            schema:
              $ref: '#/components/schemas/webhook_zone'
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: zone
      tags:
      - tag:SAMPLES:CONFIGURE:Webhook Samples
      - Webhook Samples
components:
  responses:
    HTTP400:
      $ref: ../components/responses/HTTP400.yml
    OK:
      $ref: ../components/responses/OK.yml
  schemas:
    webhook_alarms:
      $ref: ../components/schemas/webhook_alarms.yml
    webhook_asset_raw:
      $ref: ../components/schemas/webhook_asset_raw.yml
    webhook_audits:
      $ref: ../components/schemas/webhook_audits.yml
    webhook_client_info:
      $ref: ../components/schemas/webhook_client_info.yml
    webhook_client_join:
      $ref: ../components/schemas/webhook_client_join.yml
    webhook_client_latency:
      $ref: ../components/schemas/webhook_client_latency.yml
    webhook_client_sessions:
      $ref: ../components/schemas/webhook_client_sessions.yml
    webhook_device_events:
      $ref: ../components/schemas/webhook_device_events.yml
    webhook_device_updowns:
      $ref: ../components/schemas/webhook_device_updowns.yml
    webhook_discovered_raw_rssi:
      $ref: ../components/schemas/webhook_discovered_raw_rssi.yml
    webhook_location:
      $ref: ../components/schemas/webhook_location.yml
    webhook_nac_accounting:
      $ref: ../components/schemas/webhook_nac_accounting.yml
    webhook_nac_events:
      $ref: ../components/schemas/webhook_nac_events.yml
    webhook_occupancy_alerts:
      $ref: ../components/schemas/webhook_occupancy_alerts.yml
    webhook_ping:
      $ref: ../components/schemas/webhook_ping.yml
    webhook_sdkclient-scan-data:
      $ref: ../components/schemas/webhook_sdkclient-scan-data.yml
    webhook_site_sle:
      $ref: ../components/schemas/webhook_site_sle.yml
    webhook_zone:
      $ref: ../components/schemas/webhook_zone.yml
  securitySchemes:
    apiToken:
      description: "Like many other API providers, it\u2019s also possible to generate\
        \ API Tokens to be used (in HTTP Header) for authentication. An API token\
        \ ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token\
        \ value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated\
        \ for a specific admin has the same privilege as the user\n* an API token\
        \ will be automatically removed if not used for > 90 days\n* SSO admins cannot\
        \ generate these API tokens. Refer Org level API tokens which can have privileges\
        \ of a specific Org/Site for more information."
      in: header
      name: Authorization
      type: apiKey
    basicAuth:
      description: "While our current UI uses Session / Cookie-based authentication,\
        \ it\u2019s also possible to do Basic Auth."
      scheme: basic
      type: http
