openapi: 3.0.1
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2309.1.1**

    >

    > Date: **September 28, 2023**


    ---


    #### Available Documentation

    * [Postman](https://documenter.getpostman.com/view/224925/SzYgQufe)

    * [Open API](https://doc.mist-lab.fr/)


    ---


    #### Useful links

    * [Mist Homepage](https://www.mist.com)

    * [Mist Documentation](https://www.mist.com/documentation)

    * [Official API Documentation](https://api.mist.com/api/v1/docs/Home) (Mist account
    required)

    * [Mist Blog](https://www.mist.com/news/?md_post_type=post)

    * [Mist Updates](https://www.mist.com/documentation/category/product-updates/)'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: installer
  version: 2309.1.1
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Europe 01
  url: https://api.eu.mist.com
security:
- apiToken: []
- basicAuth: []
tags:
- description: "In a typical enterprise, a separate group of people, Installers, are\
    \ responsible for install new devices. May it be a new installation (e.g. new\
    \ stores), a replacement installation (e.g. replacing Cisco APs with Mist APs),\
    \ or addition (e.g. adding new APs for better coverage). Instead of granting them\
    \ Admin/Write privilege, it's more desirable to grant them minimum privileges\
    \ to do the initial provisioning so they cannot read sensible information (e.g.\
    \ PSK of a WLAN), or change configs of running APs.\nAt a high level, Installer\
    \ APs try to achieve the following:\n1. identifying a device by MAC (that\u2019\
    s what they see)\n2. they can only touch configurations of the devices they\u2019\
    re installing\n3. allow the following configurations: * name * site assignment\
    \ * device  profile assignment * map and location (x/y) assignment * claim (if\
    \ not already in the inventory) * replace existing device with the device being\
    \ installed\n\n* Grace Period *\nGrace period provides a dynamic way to limit\
    \ what devices / sites   installer can work on. Generally installers work on recent\
    \ deployments -  bringing up new sites, add newly claimed devices to new / existing\
    \ sites. They  make mistakes, too, and may need to further tweak some of the parameters.\
    \   Default grace period is 7 days and can be set from 1 day to 365 days."
  name: Installer
paths:
  /api/v1/installer/orgs/{org_id}/alarmtemplates:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get List of alarm templates
      operationId: listInstallerAlarmTemplates
      responses:
        '200':
          $ref: '#/components/responses/InstallerAlarmtemplatesArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listInstallerAlarmTemplates
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/deviceprofiles:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get List of Device Profiles
      operationId: listInstallerDeviceProfiles
      parameters: []
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                  - id: 6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9
                    name: DeviceProfile 1
              schema:
                items:
                  properties:
                    id:
                      format: uuid
                      type: string
                    name:
                      type: string
                  required:
                  - id
                  - name
                  type: object
                minItems: 1
                type: array
                uniqueItems: true
          description: OK
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listInstallerDeviceProfiles
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/devices:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get List of recently claimed devices
      operationId: listInstallerListOfRenctlyClaimedDevices
      responses:
        '200':
          $ref: '#/components/responses/InstallerDevicesArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listInstallerListOfRenctlyClaimedDevices
      tags:
      - Installer
      - Installer
    post:
      description: This mirrors `POST /api/v1/orgs/{org_id}/inventory` (see Inventory
        API)
      operationId: claimInstallerDevices
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                - 6JG8E-PTFV2-A9Z2N
                - DVH4V-SNMSZ-PDXBR
            schema:
              $ref: '#/components/schemas/claimcodes'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/OrgInventoryAdd'
        '400':
          description: Bad Request if none of the entries are valid
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: claimInstallerDevices
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/devices/{device_mac}:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/device_mac'
    delete:
      description: Unassign recently claimed devices
      operationId: unassignInstallerRecentlyClaimedDevice
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: unassignInstallerRecentlyClaimedDevice
      tags:
      - Installer
      - Installer
    put:
      description: "Provision or Replace a device \n\nIf replacing_mac is in the request\
        \ payload, other attributes are ignored, we attempt to replace existing device\
        \ (with mac replacing_mac) with the inventory device being configured. The\
        \ replacement device must be in the inventory but not assigned, and the replacing_mac\
        \ device must be assigned to a site, and satisfy grace period requirements.\
        \ The Device replaced will become unassigned."
      operationId: provisionInstallerDevices
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  deviceprofile_name: string
                  for_site: true
                  height: 0
                  map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                  name: string
                  orientation: 0
                  site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                  site_name: string
                  x: 0
                  y: 0
            schema:
              $ref: '#/components/schemas/installer_provision_device'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              examples:
                invalid mac given for replacing_mac:
                  value:
                    detail: invalid replacing_mac
                inventory device is already assigned:
                  value:
                    detail: device already assigned
                outsite_of_grace_period:
                  value:
                    detail: outside of grace period
                replacing_mac device is not assigned to a site:
                  value:
                    detail: replacing_mac device is unassigned
                replacing_mac device last modified outside of grace period:
                  value:
                    detail: replacing_mac device outside of grace period
              schema:
                properties:
                  detail:
                    type: string
                required:
                - detail
                type: object
          description: Bad Request
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          content:
            application/json:
              examples:
                replacing_mac device is not in org inventory:
                  value:
                    detail: replacing_mac inventory not found
                replacing_mac device not found:
                  value:
                    detail: replacing_mac device not found
              schema:
                properties:
                  detail:
                    type: string
                type: object
                x-examples:
                  example-1:
                    detail: replacing_mac inventory not found
          description: Not Found
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: provisionInstallerDevices
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/devices/{device_mac}/locate:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/device_mac'
    post:
      description: "Locate a Device by blinking it\u2019s LED, it\u2019s a persisted\
        \ state that has to be stopped by calling Stop Locating API"
      operationId: startInstallerLocateDevice
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: startInstallerLocateDevice
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/devices/{device_mac}/unlocate:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/device_mac'
    post:
      description: Stop it
      operationId: stopInstallerLocateDevice
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: stopInstallerLocateDevice
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/devices/{device_mac}/{image_name}:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/image_name'
    - $ref: '#/components/parameters/device_mac'
    delete:
      description: delete image
      operationId: deleteInstallerDeviceImage
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: deleteInstallerDeviceImage
      tags:
      - Installer
      - Installer
    post:
      description: Add image
      operationId: addInstallerDeviceImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              format: binary
              type: string
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: addInstallerDeviceImage
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/rftemplates:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get List of RF Templates
      operationId: listInstallerRfTemplatesNames
      responses:
        '200':
          $ref: '#/components/responses/InstallerRftemplatesArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listInstallerRfTemplatesNames
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/secpolicies:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get List of Secuity Policies
      operationId: listInstallerSecPolicies
      responses:
        '200':
          $ref: '#/components/responses/InstallerSecpoliciesArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listInstallerSecPolicies
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/sitegroups:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get List of Site Groups
      operationId: listInstallerSiteGroups
      responses:
        '200':
          $ref: '#/components/responses/InstallerSitegroupsArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listInstallerSiteGroups
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/sites:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get List of Sites
      operationId: listInstallerSites
      responses:
        '200':
          $ref: '#/components/responses/InstallerSitesArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listInstallerSites
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/sites/{site_name}:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/site_name'
    put:
      description: Often the Installers are asked to assign Devices to Sites. The
        Sites can either be pre-created or created/modified by the Installer. If this
        is an update, the same grace period also applies.
      operationId: createOrUpdateInstallerSites
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  address: 1601 S. Deanza Blvd., Cupertino, CA, 95014
                  country_code: US
                  latlng:
                    lat: 37.295833
                    lng: -122.032946
                  name: string
                  rftemplate_name: rftemplate1
                  sitegroup_names:
                  - sg1
                  - sg2
                  timezone: America/Los_Angeles
            schema:
              $ref: '#/components/schemas/installer_site'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: createOrUpdateInstallerSites
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/sites/{site_name}/maps:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/site_name'
    get:
      description: Get List of Maps
      operationId: listInstallerMaps
      responses:
        '200':
          $ref: '#/components/responses/MapsArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listInstallerMaps
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/sites/{site_name}/maps/import:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/site_name'
    post:
      description: Import data from files is a multipart POST which has an file, an
        optional json, and an optional csv, to create floorplan, assign & place ap
        if name or mac matches
      operationId: importInstallerMap
      requestBody:
        content:
          multipart/form-data:
            examples:
              Example:
                value:
                  csv: string
                  file: string
                  json:
                    import_all_floorplans: false
                    import_height: false
                    import_orientation: false
                    vendor_name: ekahau
            schema:
              $ref: '#/components/schemas/import_site_map'
      responses:
        '200':
          $ref: '#/components/responses/MapImport'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: importInstallerMap
      tags:
      - Installer
      - Installer
  /api/v1/installer/orgs/{org_id}/sites/{site_name}/maps/{map_id}:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/site_name'
    - $ref: '#/components/parameters/map_id'
    delete:
      description: Delete Map
      operationId: deleteInstallerMap
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: deleteInstallerMap
      tags:
      - Installer
      - Installer
    post:
      description: Create a MAP
      operationId: createInstallerMap
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  flags: {}
                  height: 0
                  latlng_br:
                    lat: string
                    lng: string
                  latlng_tl:
                    lat: string
                    lng: string
                  locked: true
                  name: string
                  orientation: 0
                  origin_x: 0
                  origin_y: 0
                  ppm: 0
                  sitesurvey_path:
                  - coordinate: string
                    id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                    name: string
                    nodes:
                    - edges:
                        N2: string
                      name: string
                      position:
                        x: 0
                        y: 0
                  thumbnail_url: string
                  type: image
                  url: string
                  view: roadmap
                  wall_path:
                    coordinate: string
                    nodes:
                    - edges:
                        N2: string
                      name: string
                      position:
                        x: 0
                        y: 0
                  wayfinding:
                    micello:
                      account_key: string
                      default_level_id: 0
                      map_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                    snap_to_path: true
                  wayfinding_path:
                    coordinate: string
                    nodes:
                    - edges:
                        N2: string
                      name: string
                      position:
                        x: 0
                        y: 0
                  width: 0
            schema:
              $ref: '#/components/schemas/map'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/Map'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: createInstallerMap
      tags:
      - Installer
      - Installer
    put:
      description: Update map
      operationId: updateInstallerMap
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/map'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/Map'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: updateInstallerMap
      tags:
      - Installer
      - Installer
  /api/v1/installer/sites/{site_name}/optimize:
    parameters:
    - $ref: '#/components/parameters/site_name'
    get:
      description: "After installation is considered complete (APs are placed on maps,\
        \ all powered up), you can trigger an optimize operation where RRM will kick\
        \ in (and maybe other things in the future) before it\u2019s automatically\
        \ scheduled."
      operationId: optimizeInstallerRrm
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: optimizeInstallerRrm
      tags:
      - Installer
      - Installer
components:
  parameters:
    device_mac:
      in: path
      name: device_mac
      required: true
      schema:
        example: 0000000000ab
        pattern: ^[0-9a-fA-F]{12}$
        type: string
    image_name:
      in: path
      name: image_name
      required: true
      schema:
        type: string
    map_id:
      in: path
      name: map_id
      required: true
      schema:
        example: 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    org_id:
      in: path
      name: org_id
      required: true
      schema:
        example: 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    site_name:
      in: path
      name: site_name
      required: true
      schema:
        type: string
  responses:
    InstallerAlarmtemplatesArray:
      content:
        application/json:
          examples:
            Example 1:
              value:
              - id: 684dfc5c-fe77-2290-eb1d-ef3d677fe168
                name: AlarmTemplate 1
          schema:
            items:
              $ref: '#/components/schemas/installer_list'
            type: array
      description: Installer List of Alarm Templates
    HTTP400:
      content:
        application/json:
          examples:
            Example:
              value:
                detail: 'JSON parse error - Expecting value: line 5 column 8 (char
                  56)'
          schema:
            properties:
              detail:
                example: 'JSON parse error - Expecting value: line 5 column 8 (char
                  56)'
                type: string
            type: object
            x-examples:
              Example 1:
                detail: JSON parse error
      description: Bad Syntax
    HTTP401:
      content:
        application/json:
          examples:
            Example:
              value:
                detail: Authentication credentials were not provided.
          schema:
            properties:
              detail:
                example: Authentication credentials were not provided.
                type: string
            type: object
            x-examples:
              Example 1:
                detail: Authentication credentials were not provided.
      description: Unauthorized
    HTTP403:
      content:
        application/json:
          examples:
            Example:
              value:
                detail: You do not have permission to perform this action.
          schema:
            properties:
              detail:
                example: You do not have permission to perform this action.
                type: string
            type: object
            x-examples:
              Example 1:
                detail: You do not have permission to perform this action.
      description: Permission Denied
    HTTP404:
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
      description: "Not found. The API endpoint doesn\u2019t exist or resource doesn\u2019\
        t exist"
    HTTP429:
      content:
        application/json:
          examples:
            Example:
              value:
                detail: Too Many Request. The API Token used for the request reached
                  the 5000 API Calls per hour threshold
          schema:
            properties:
              detail:
                example: Too Many Request. The API Token used for the request reached
                  the 5000 API Calls per hour threshold
                type: string
            type: object
        application/xml:
          schema:
            properties: {}
            type: object
      description: Too Many Request. The API Token used for the request reached the
        5000 API Calls per hour threshold
    InstallerDevicesArray:
      content:
        application/json:
          examples:
            Example:
              value:
              - connected: true
                deviceprofile_name: SJ1
                height: 2.7
                mac: 5c5b35000018
                map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                model: AP41
                name: hallway
                orientation: 90
                serial: FXLH2015150025
                site_name: SJ1
                x: 150
                y: 300
          schema:
            items:
              $ref: '#/components/schemas/installer_device'
            type: array
      description: List of Devices Recently Claimed
    OrgInventoryAdd:
      content:
        application/json:
          examples:
            Example:
              value:
                added:
                - 6JG8E-PTFV2-A9Z2N
                duplicated:
                - DVH4V-SNMSZ-PDXBR
                error:
                - PO1025335ohoh
                inventory_added:
                - mac: 5c5b35000018
                  magic: 6JG8EPTFV2A9Z2N
                  model: AP41
                  serial: FXLH2015150025
                  type: ap
                inventory_duplicated:
                - mac: 5c5b35000012
                  magic: DVH4VSNMSZPDXBR
                  model: AP41
                  serial: FXLH2015150027
                  type: ap
          schema:
            $ref: '#/components/schemas/response_inventory'
      description: "OK - if any of entries are valid or there\u2019s no errors"
    OK:
      content:
        application/json:
          schema:
            type: object
      description: OK
    InstallerRftemplatesArray:
      content:
        application/json:
          examples:
            Example 1:
              value:
              - id: bb8a9017-1e36-5d6c-6f2b-551abe8a76a2
                name: RFTemplate 1
          schema:
            items:
              $ref: '#/components/schemas/installer_list'
            type: array
      description: Installer List of RF Templates
    InstallerSecpoliciesArray:
      content:
        application/json:
          examples:
            Example 1:
              value:
              - id: 3bcd0beb-5d0a-4cbd-92c1-14aea91e98ef
                name: SecuPolicy 1
          schema:
            items:
              $ref: '#/components/schemas/installer_list'
            type: array
      description: Installer List of Security Policies
    InstallerSitegroupsArray:
      content:
        application/json:
          examples:
            Example 1:
              value:
              - id: 581328b6-e382-f54e-c9dc-999983183a34
                name: SiteGroup 1
          schema:
            items:
              $ref: '#/components/schemas/installer_list'
            type: array
      description: Installer List of Site Groups
    InstallerSitesArray:
      content:
        application/json:
          examples:
            Example:
              value:
              - address: 1601 S. Deanza Blvd., Cupertino, CA, 95014
                country_code: US
                id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                latlng:
                  lat: 37.295833
                  lng: -122.032946
                name: Mist Office
                rftemplate_name: rftemplate1
                sitegroup_names:
                - sg1
                - sg2
                timezone: America/Los_Angeles
          schema:
            items:
              $ref: '#/components/schemas/installer_site'
            type: array
      description: List of Sites
    MapsArray:
      content:
        application/json:
          examples:
            example-1:
              value:
              - created_time: 0
                flags: {}
                height: 0
                height_m: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                latlng_br:
                  lat: string
                  lng: string
                latlng_tl:
                  lat: string
                  lng: string
                locked: true
                modified_time: 0
                name: string
                occupancy_limit: 0
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                orientation: 0
                origin_x: 0
                origin_y: 0
                ppm: 0
                site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                sitesurvey_path:
                - coordinate: string
                  id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  name: string
                  nodes:
                  - edges:
                      N2: string
                    name: string
                    position:
                      x: 0
                      y: 0
                thumbnail_url: string
                type: image
                url: string
                view: roadmap
                wall_path:
                  coordinate: string
                  nodes:
                  - edges:
                      N2: string
                    name: string
                    position:
                      x: 0
                      y: 0
                wayfinding:
                  micello:
                    account_key: string
                    default_level_id: 0
                    map_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  snap_to_path: true
                wayfinding_path:
                  coordinate: string
                  nodes:
                  - edges:
                      N2: string
                    name: string
                    position:
                      x: 0
                      y: 0
                width: 0
                width_m: 0
          schema:
            items:
              $ref: '#/components/schemas/map'
            type: array
      description: OK
    MapImport:
      content:
        application/json:
          examples:
            example-assigned_and_placed:
              value:
                aps:
                - action: assigned-placed
                  floorplan_id: 6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9
                  height: 3
                  mac: 5c5b35000001
                  map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                  orientation: 45
                floorplans:
                - action: imported
                  id: cbdb7f0b-3be0-4872-88f9-58790b509c23
                  map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                  name: map1
                site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                summary:
                  num_ap_assigned: 1
                  num_inv_assigned: 1
                  num_map_assigned: 1
            example-assigned_named_and_placed:
              value:
                aps:
                - action: assigned-named-placed
                  floorplan_id: 6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9
                  mac: 5c5b35000001
                  map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                  orientation: 45
                floorplans:
                - action: imported
                  id: cbdb7f0b-3be0-4872-88f9-58790b509c23
                  map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                  name: map1
                site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                summary:
                  num_ap_assigned: 1
                  num_inv_assigned: 1
                  num_map_assigned: 1
            example-placed:
              value:
                aps:
                - action: placed
                  floorplan_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  height: 3
                  mac: 5c5b35000001
                  map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                  orientation: 45
                floorplans:
                - action: imported
                  id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                  name: map1
                site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                summary:
                  num_ap_assigned: 1
                  num_inv_assigned: 1
                  num_map_assigned: 1
          schema:
            properties:
              aps:
                items:
                  properties:
                    action:
                      enum:
                      - placed
                      - assigned-placed
                      - named-placed
                      - assigned-named-placed
                      - ignored
                      type: string
                    floorplan_id:
                      format: uuid
                      type: string
                    height:
                      type: number
                    mac:
                      type: string
                    map_id:
                      format: uuid
                      type: string
                    orientation:
                      type: number
                    reason:
                      type: string
                  required:
                  - mac
                  - action
                  - map_id
                  - floorplan_id
                  - orientation
                  type: object
                minItems: 1
                type: array
                uniqueItems: true
              floorplans:
                items:
                  properties:
                    action:
                      type: string
                    id:
                      format: uuid
                      type: string
                    map_id:
                      format: uuid
                      type: string
                    name:
                      type: string
                    reason:
                      type: string
                  required:
                  - id
                  - name
                  - action
                  - map_id
                  type: object
                minItems: 1
                type: array
                uniqueItems: true
              for_site:
                readOnly: true
                type: boolean
              site_id:
                format: uuid
                type: string
              summary:
                properties:
                  num_ap_assigned:
                    type: integer
                  num_inv_assigned:
                    type: integer
                  num_map_assigned:
                    type: integer
                required:
                - num_ap_assigned
                - num_map_assigned
                - num_inv_assigned
                type: object
            required:
            - site_id
            - aps
            - floorplans
            - summary
            type: object
      description: OK
    Map:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/map'
      description: OK
  schemas:
    claimcodes:
      description: List of Claim Codes
      example:
      - 6JG8E-PTFV2-A9Z2N
      - DVH4V-SNMSZ-PDXBR
      items:
        description: claim code
        type: string
      title: claimcodes
      type: array
      x-examples:
        Example:
        - 6JG8E-PTFV2-A9Z2N
        - DVH4V-SNMSZ-PDXBR
      x-stoplight:
        id: 0f9retkg6nqxq
    installer_provision_device:
      description: Provision Device
      properties:
        deviceprofile_name:
          example: SJ1
          type: string
        for_site:
          readOnly: true
          type: boolean
        height:
          example: 2.7
          type: number
        map_id:
          example: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
          format: uuid
          type: string
        name:
          example: SJ1-AP1
          type: string
        orientation:
          example: 90
          type: number
        replacing_mac:
          description: Onlif this is to replace an existing device
          example: 5c5b3500003
          type: string
        role:
          description: optional role for switch / gateway
          type: string
        site_id:
          example: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
          format: uuid
          readOnly: true
          type: string
        site_name:
          example: SJ1
          type: string
        x:
          example: 150
          type: number
        y:
          example: 300
          type: number
      required:
      - name
      type: object
      x-examples:
        Example:
          deviceprofile_name: SJ1
          for_site: true
          height: 2.7
          map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
          name: SJ1-AP1
          orientation: 90
          replacing_mac: 5c5b3500003
          role: string
          site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
          site_name: SJ1
          x: 150
          y: 300
      x-stoplight:
        id: b4cc9c7f47b56
    installer_site:
      properties:
        address:
          example: 1601 S. Deanza Blvd., Cupertino, CA, 95014
          type: string
        country_code:
          example: US
          type: string
        id:
          example: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
          format: uuid
          type: string
        latlng:
          properties:
            lat:
              example: 37.295833
              type: number
            lng:
              example: -122.032946
              type: number
          required:
          - lat
          type: object
        name:
          example: Mist Office
          type: string
        rftemplate_name:
          example: rftemplate1
          type: string
        sitegroup_names:
          example:
          - sg1
          - sg2
          items:
            type: string
          type: array
        timezone:
          example: America/Los_Angeles
          type: string
      required:
      - address
      - country_code
      - latlng
      - name
      title: installer_site
      type: object
      x-stoplight:
        id: wg4eibzsp1j6c
    import_site_map:
      properties:
        auto_deviceprofile_assignment:
          description: whether to auto assign device to deviceprofile by name
          example: true
          type: boolean
        csv:
          description: csv file for ap name mapping, optional
          format: binary
          type: string
        file:
          description: ekahau or ibwave file
          format: binary
          type: string
        json:
          properties:
            import_all_floorplans:
              default: false
              type: boolean
            import_height:
              default: true
              type: boolean
            import_orientation:
              default: true
              type: boolean
            vendor_name:
              enum:
              - ekahau
              - ibwave
              example: ekahau
              type: string
          required:
          - vendor_name
          type: object
      title: import_site_map
      type: object
      x-stoplight:
        id: q9r6durtxytsj
    map:
      description: Map
      properties:
        created_time:
          readOnly: true
          type: number
        flags:
          additionalProperties:
            type: integer
          description: name/val pair objects for location engine to use
          example:
            assetHoldTime: 5
            storeTime: 10
          type: object
        for_site:
          readOnly: true
          type: boolean
        height:
          description: when type=image, height of the image map
          example: 1500
          type: integer
        height_m:
          type: number
        id:
          format: uuid
          readOnly: true
          type: string
        latlng_br:
          description: when type=google, latitude / longitude of the bottom-right
            corner
          properties:
            lat:
              type: string
            lng:
              type: string
          type: object
        latlng_tl:
          description: when type=google, latitude / longitude of the top-left corner
          properties:
            lat:
              type: string
            lng:
              type: string
          type: object
        locked:
          default: false
          description: whether this map is considered locked down
          type: boolean
        modified_time:
          readOnly: true
          type: number
        name:
          description: The name of the map
          example: Mist Office
          type: string
        occupancy_limit:
          type: integer
        org_id:
          format: uuid
          readOnly: true
          type: string
        orientation:
          default: 0
          description: orientation of the map, 0 means up is north, 90 means up is
            west
          example: 30
          type: integer
        origin_x:
          description: the user-annotated x origin, pixels
          example: 35
          type: integer
        origin_y:
          description: the user-annotated y origin, pixels
          example: 60
          type: integer
        ppm:
          description: when type=image, pixels per meter
          example: 40.94
          type: number
        site_id:
          format: uuid
          readOnly: true
          type: string
        sitesurvey_path:
          description: sitesurvey_path
          items:
            properties:
              coordinate:
                example: actual
                type: string
              id:
                example: 63eda950-c6da-11e4-a628-60f81dd250ce
                format: uuid
                type: string
              name:
                example: Default
                type: string
              nodes:
                items:
                  $ref: '#/components/schemas/map_node'
                minItems: 0
                type: array
            type: object
          minItems: 0
          type: array
        thumbnail_url:
          description: when type=image, the url for the thumbnail image / preview
          example: https://url/to/image.png
          readOnly: true
          type: string
        type:
          default: image
          enum:
          - image
          - google
          example: image
          type: string
        url:
          description: when type=image, the url
          example: https://url/to/image.png
          readOnly: true
          type: string
        use_auto_orientation:
          default: false
          description: whether this map uses autooreintation values or ignores them
          type: boolean
        use_auto_placement:
          default: false
          description: whether this map uses autoplacement values or ignores them
          type: boolean
        view:
          description: when type=google
          enum:
          - roadmap
          - satellite
          - hybrid
          - terrain
          - null
          nullable: true
          type: string
        wall_path:
          description: a JSON blob for wall definition (same format as wayfinding_path)
          properties:
            coordinate:
              example: actual
              type: string
            nodes:
              items:
                $ref: '#/components/schemas/map_node'
              minItems: 0
              type: array
          type: object
        wayfinding:
          description: properties related to wayfinding
          properties:
            micello:
              properties:
                account_key:
                  example: adasdf
                  type: string
                default_level_id:
                  example: 5
                  type: integer
                map_id:
                  example: c660f81dd250c
                  type: string
              type: object
            snap_to_path:
              type: boolean
          type: object
        wayfinding_path:
          description: "a JSON blob for wayfinding (using Dijkstra\u2019s algorithm)"
          properties:
            coordinate:
              example: actual
              type: string
            nodes:
              items:
                $ref: '#/components/schemas/map_node'
              minItems: 0
              type: array
          type: object
        width:
          description: when type=image, width of the image map
          example: 1250
          type: integer
        width_m:
          type: number
      type: object
      x-examples:
        example-google:
          latlng_br:
            lat: 37.295285
            lng: -122.032789
          latlng_tl:
            lat: 37.295057
            lng: -122.033095
          name: Oakridge Mall
          origin_x: -122.03301
          origin_y: 37.29508
          type: google
          view: roadmap
        example-image:
          flags:
            assetHoldTime: 5
            storeTime: 10
          for_site: true
          height: 1500
          locked: false
          name: Mist Office
          occupancy_limit: 0
          origin_x: 35
          origin_y: 60
          ppm: 40.94
          site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
          sitesurvey_path:
          - coordinate: actual
            id: cbdb7f0b-3be0-4872-88f9-58790b509c23-j68kows8
            name: Default
            nodes:
            - edges:
                N1: '1'
              name: N1
              position:
                x: 746
                y: 104
          thumbnail_url: https://url/to/image.png
          type: image
          url: https://url/to/image.png
          use_auto_orientation: false
          use_auto_placement: false
          wall_path:
            coordinate: actual
            nodes:
            - edges:
                N1: '1'
              name: N1
              position:
                x: 746
                y: 104
          wayfinding:
            micello:
              account_key: adasdf
              default_level_id: 5
              map_id: c660f81dd250c
            snap_to_path: true
          wayfinding_path:
            coordinate: actual
            nodes:
            - edges:
                N1: '1'
              name: N1
              position:
                x: 746
                y: 104
          width: 1250
    map_node:
      description: Nodes on maps
      properties:
        edges:
          additionalProperties:
            type: string
          example:
            N1: '1'
          type: object
        name:
          example: N1
          type: string
        position:
          properties:
            x:
              example: 746
              type: number
            y:
              example: 104
              type: number
          required:
          - x
          - y
          type: object
      required:
      - name
      type: object
    installer_list:
      properties:
        id:
          example: 684dfc5c-fe77-2290-eb1d-ef3d677fe168
          type: string
        name:
          example: 'Entry #1'
          type: string
      type: object
      x-examples: {}
    installer_device:
      properties:
        connected:
          example: true
          type: boolean
        deviceprofile_name:
          example: SJ1
          type: string
        ext_ip:
          example: 12.34.56.78
          type: string
        height:
          example: 2.7
          type: number
        ip:
          example: 192.168.1.111
          type: string
        last_seen:
          example: 1687887907.5919843
          type: number
        mac:
          example: 5c5b35000018
          type: string
        map_id:
          example: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
          format: uuid
          type: string
        model:
          example: AP41
          type: string
        name:
          example: hallway
          type: string
        orientation:
          example: 90
          type: number
        serial:
          example: FXLH2015150025
          type: string
        site_name:
          example: SJ1
          type: string
        uptime:
          example: 12345
          type: integer
        vc_mac:
          example: null
          nullable: true
          type: string
        version:
          example: 0.10.24362
          type: string
        x:
          example: 150
          type: number
        y:
          example: 300
          type: number
      title: installer_device
      type: object
      x-examples: {}
      x-stoplight:
        id: nmap2ho8snv3o
    response_inventory:
      properties:
        added:
          items:
            example: 6JG8E-PTFV2-A9Z2N
            type: string
          type: array
        duplicated:
          items:
            example: DVH4V-SNMSZ-PDXBR
            type: string
          type: array
        error:
          items:
            example: PO1025335ohoh
            type: string
          type: array
        inventory_added:
          items:
            properties:
              mac:
                example: 5c5b35000018
                type: string
              magic:
                example: 6JG8EPTFV2A9Z2N
                type: string
              model:
                example: AP41
                type: string
              serial:
                example: FXLH2015150025
                type: string
              type:
                example: ap
                type: string
            required:
            - mac
            - magic
            - model
            - serial
            - type
            type: object
          minItems: 1
          type: array
          uniqueItems: true
        inventory_duplicated:
          items:
            properties:
              mac:
                example: 5c5b35000012
                type: string
              magic:
                example: DVH4VSNMSZPDXBR
                type: string
              model:
                example: AP41
                type: string
              serial:
                example: FXLH2015150027
                type: string
              type:
                example: ap
                type: string
            required:
            - mac
            - magic
            - model
            - serial
            - type
            type: object
          minItems: 1
          type: array
          uniqueItems: true
      readOnly: true
      type: object
      x-examples:
        example-1:
          added:
          - string
          duplicated:
          - string
          error:
          - string
          inventory_added:
          - mac: string
            magic: string
            model: string
            serial: string
            type: string
          inventory_duplicated:
          - mac: string
            magic: string
            model: string
            serial: string
            type: string
  securitySchemes:
    apiToken:
      description: "Like many other API providers, it\u2019s also possible to generate\
        \ API Tokens to be used (in HTTP Header) for authentication. An API token\
        \ ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token\
        \ value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated\
        \ for a specific admin has the same privilege as the user\n* an API token\
        \ will be automatically removed if not used for > 90 days\n* SSO admins cannot\
        \ generate these API tokens. Refer Org level API tokens which can have privileges\
        \ of a specific Org/Site for more information."
      in: header
      name: Authorization
      type: apiKey
    basicAuth:
      description: "While our current UI uses Session / Cookie-based authentication,\
        \ it\u2019s also possible to do Basic Auth."
      scheme: basic
      type: http
