openapi: 3.0.1
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2306.1.6**

    >

    > Date: **June 21, 2023**


    ---


    #### Available Documentation

    * [Postman](https://documenter.getpostman.com/view/224925/SzYgQufe)

    * [Open API](https://doc.mist-lab.fr/)


    ---


    #### Useful links

    * [Mist Homepage](https://www.mist.com)

    * [Mist Documentation](https://www.mist.com/documentation)

    * [Official API Documentation](https://api.mist.com/api/v1/docs/Home) (Mist account
    required)

    * [Mist Blog](https://www.mist.com/news/?md_post_type=post)

    * [Mist Updates](https://www.mist.com/documentation/category/product-updates/)'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist API
  version: 2306.1.6
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Europe 01
  url: https://api.eu.mist.com
security:
- apiToken: []
- basicAuth: []
tags:
- description: "Like many other API providers, it\u2019s also possible to generate\
    \ API Tokens to be used (in HTTP Header) for authentication. An API token ties\
    \ to a Admin with equal or less privileges.\n\nNotes:\n* an API token generated\
    \ for a specific admin has the same privilege as the user\n* an API token will\
    \ be automatically removed if not used for > 90 days\n* SSO admins cannot generate\
    \ these API tokens. Refer Org level API tokens (/api/v1/docs/Org#api-token) which\
    \ can have privileges of a specific Org/Site for more information."
  name: API Token
paths:
  /api/v1/self/apitokens:
    get:
      description: Get List of Current User API Tokens
      operationId: listApiTokens
      responses:
        '200':
          $ref: '#/components/responses/ApitokensArray'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: listApiTokens
      tags:
      - API Token
      - Configuration
    post:
      description: 'Create API Token

        Note that the key is only available during creation time.'
      operationId: createApiToken
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
              type: object
      responses:
        '200':
          $ref: '#/components/responses/Apitoken'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: createApiToken
      tags:
      - API Token
      - Configuration
  /api/v1/self/apitokens/{apitoken_id}:
    delete:
      description: Delete an API Token
      operationId: deleteApiToken
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: deleteApiToken
      tags:
      - API Token
      - Configuration
    parameters:
    - in: path
      name: apitoken_id
      required: true
      schema:
        type: string
    put:
      description: Update API Token
      operationId: updateApiToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./components/schemas/apitoken.yaml
      responses:
        '200':
          $ref: '#/components/responses/Apitoken'
      summary: updateApiToken
      tags:
      - API Token
      - Configuration
components:
  parameters: {}
  responses:
    Apitoken:
      content:
        application/json:
          examples:
            Org API Token:
              value:
                created_time: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                key: string
                last_used: 0
                name: string
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                privileges:
                - msp_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  msp_name: string
                  name: string
                  org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  org_name: string
                  orggroup_ids:
                  - b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  role: admin
                  scope: org
                  site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  sitegroup_ids:
                  - 6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9
            User API Token:
              value:
                created_time: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                key: string
                last_used: 0
                name: string
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
          schema:
            $ref: ./components/schemas/apitoken.yaml
      description: OK
    ApitokensArray:
      content:
        application/json:
          examples:
            Org API Tokens:
              value:
              - created_time: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                key: string
                last_used: 0
                name: string
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                privileges:
                - msp_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  msp_name: string
                  name: string
                  org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  org_name: string
                  orggroup_ids:
                  - b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  role: admin
                  scope: org
                  site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  sitegroup_ids:
                  - b069b358-4c97-5319-1f8c-7c5ca64d6ab1
            User API Tokens:
              value:
              - created_time: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                key: string
                last_used: 0
                name: string
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
          schema:
            items:
              $ref: ./components/schemas/apitoken.yaml
            type: array
      description: OK
    OK:
      content:
        application/json:
          schema:
            type: object
      description: OK
