openapi: 3.0.1
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2306.1.6**

    >

    > Date: **June 21, 2023**


    ---


    #### Available Documentation

    * [Postman](https://documenter.getpostman.com/view/224925/SzYgQufe)

    * [Open API](https://doc.mist-lab.fr/)


    ---


    #### Useful links

    * [Mist Homepage](https://www.mist.com)

    * [Mist Documentation](https://www.mist.com/documentation)

    * [Official API Documentation](https://api.mist.com/api/v1/docs/Home) (Mist account
    required)

    * [Mist Blog](https://www.mist.com/news/?md_post_type=post)

    * [Mist Updates](https://www.mist.com/documentation/category/product-updates/)'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist API
  version: 2306.1.6
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Europe 01
  url: https://api.eu.mist.com
security:
- apiToken: []
- basicAuth: []
tags:
- name: Authentication
- name: Monitor
- name: Operational
- name: Login
- description: A Mist account can be linked to OAuth2 providers:\n1. First, login
    with your Mist account\n2. Obtain the Authorization URL for Linking 1. in JSON
    response, more usable for developers. Simply don\'t specify the forward parameter
    when obtaining the authorization URL 2. or as GET parameter, for UI where the
    user flow can be continued. Specify the landing page/url of your choice 3. Obtain
    the authorizaiton code by clicking / going through Authorization URL Link Mist
    Account against OAuth2 Provider by using the authorization code
  name: Login With OAuth2
- description: "Like many other API providers, it\u2019s also possible to generate\
    \ API Tokens to be used (in HTTP Header) for authentication. An API token ties\
    \ to a Admin with equal or less privileges.\n\nNotes:\n* an API token generated\
    \ for a specific admin has the same privilege as the user\n* an API token will\
    \ be automatically removed if not used for > 90 days\n* SSO admins cannot generate\
    \ these API tokens. Refer Org level API tokens (/api/v1/docs/Org#api-token) which\
    \ can have privileges of a specific Org/Site for more information."
  name: API Token
- description: "In a typical enterprise, a separate group of people, Installers, are\
    \ responsible for install new devices. May it be a new installation (e.g. new\
    \ stores), a replacement installation (e.g. replacing Cisco APs with Mist APs),\
    \ or addition (e.g. adding new APs for better coverage). Instead of granting them\
    \ Admin/Write privilege, it's more desirable to grant them minimum privileges\
    \ to do the initial provisioning so they cannot read sensible information (e.g.\
    \ PSK of a WLAN), or change configs of running APs.\nAt a high level, Installer\
    \ APs try to achieve the following:\n1. identifying a device by MAC (that\u2019\
    s what they see)\n2. they can only touch configurations of the devices they\u2019\
    re installing\n3. allow the following configurations: * name * site assignment\
    \ * device  profile assignment * map and location (x/y) assignment * claim (if\
    \ not already in the inventory) * replace existing device with the device being\
    \ installed\n\n* Grace Period *\nGrace period provides a dynamic way to limit\
    \ what devices / sites   installer can work on. Generally installers work on recent\
    \ deployments -  bringing up new sites, add newly claimed devices to new / existing\
    \ sites. They  make mistakes, too, and may need to further tweak some of the parameters.\
    \   Default grace period is 7 days and can be set from 1 day to 365 days."
  name: Installer
- name: Admin
- name: Mobile
- description: MSP (Managed Service Provider) contains multiple Organizations.
  name: Msps
- name: Msps Admins
- name: Msps Inventory
- name: Msps Invites
- name: Msps Logo
- name: Msps Logs
- name: Msps Licenses
- name: Msps Marvis
- name: Msps Org Groups
- name: Msps Orgs
- name: Msps SLEs
- name: Msps SSO Roles
- name: Msps SSO
- name: Msps Stats
- name: Msps Tickets
- description: An organization usually represents a customer - which has inventories,
    licenses. An Organization can contain multiple sites. A site usually represents
    a deployment at the same location (a campus, an office).
  name: Orgs
- name: Orgs 128T
- name: Orgs Admins
- description: Alarms are triggered based on certain events. Alarms could be configured
    using an Alarm Template.
  name: Orgs Alarms
- description: An Alarm Template is a set of Alarm Rules that could be applied to
    one or more sites (while each site can only pick one Alarm Template), or to the
    whole org.
  name: Orgs Alarm Templates
- name: Orgs AP Templates
- name: Orgs API Tokens
- name: Orgs Assets
- name: Orgs Asset Filters
- name: Orgs Calls
- name: Orgs Cert
- name: Orgs Clients - Wan
- name: Orgs Clients - Wired
- name: Orgs Clients - Wireless
- name: Orgs CRL
- description: 'While Templates / RF Templates / Network Templates / Gateway Templates
    provides powerful ways to control how a Device\''s configuration is derived for
    a Site. There are cases where you\''d like another level of control at the Org
    Level.

    A Device Profile contains a subset of Device\''s configurations you\''d like a
    device to have. It will be merged at runtime when we\''re provisioning an AP.'
  name: Orgs Device Profiles
- name: Orgs Devices
- description: 'EVPN allows an alternative but more efficient LAN architecture utilizing
    VxLAN / MP-BGP - separating control plane (MAC / IP Learning) from forwarding
    plane.

    In our implementation, following the steps to deploy EVPN topologies in a Site'
  name: Orgs EVPN Topologies
- description: API Call for 3rd party devices
  name: Orgs Devices Others
- name: Orgs Devices Stats
- name: Orgs Devices Upgrades
- description: "In Zscaler UI \n 1. add Partner Integration at https://admin.zscalerbeta.net/#administration/partner-integration\
    \ \n 2. Add Partner Administrator Role at https://admin.zscalerbeta.net/#administration/role-management\
    \ - Name: Mist - Access: Full \n 3. add Partner Admin at https://admin.zscalerbeta.net/#administration/admin-management\
    \ with - Login ID: john - email: john@abc.com \n 4. Find the cloud name for ZIA\
    \ https://help.zscaler.com/zia/what-my-cloud-name-zia\n"
  name: Orgs Devices Zscaler
- description: Gateway Template is applied to a site for gateway(s) in a site.
  name: Orgs Gateway Templates
- name: Orgs Guests
- name: Orgs Inventory
- name: Orgs JSE
- description: "Juniper Support Insight is a free service provided to all Mist customers.\
    \ You can adopt your devices via a few lines CLI comands. Allowing you to \n*\
    \ get some basic information about the adopted devices \n* web shell into device\
    \ (write privilege required) \n* upgrade (write privilege required)"
  name: Orgs JSI
- name: Orgs Licenses
- name: Orgs Logs
- name: Orgs Marvis
- name: Orgs Maps
- name: Orgs MxClusters
- name: Orgs MxEdges
- name: Orgs MxTunnels
- description: 'nactags are the building blocks to compose nacrules.

    They can either appear in the "matching" / "not_matching" sections of a nacrule,
    in which case they play the role of classifiers, or they could appear in the "apply_tags"
    section of the of a nacrule, in which case they influence the result.

    When the "type" field of nactag is "match", it can be used as the classfier of
    a nacrule. "match" field specifies the attribute name and "values" field specifies
    the list of attribute values to match on. When multiple values are specified,
    its treated as an OR condition between those values.

    When the "type" field of nactag is NOT "match", it can be used as the result of
    a nacrule. "type" field identifies the action to take and the corresponding field
    would provide any associated parameters to that action.'
  name: Orgs NAC Tags
- name: Orgs NAC Rules
- description: 'Network template is intended to be applied to a Site. It works like
    a blueprint of the network of the site.

    All Site Settings can go into Network Templates. See Site:Site Setting for schema

    Moreover, this can further be overwriten by individual Site Setting'
  name: Orgs Network Templates
- name: Orgs Networks
- name: Orgs OAuth
- name: Orgs Premium Analytics
- name: Orgs Psks
- description: "PSK Self-Service Portals are for \n  1. **WIFI users** who want to\
    \ connect to a WLAN with personal PSK, they\u2019re told to connect to a URL where\
    \ they can login (likely through company\u2019s SSO) and get the WIFI Name / Passphrase\
    \ - required input fields name, email so we can generate PSK \n  2. **PSK Admins**\
    \ (they don\u2019t have access to normal Network Admin Portal)\nWhen a PSK portal\
    \ is created, an unique URL will be generated (e.g. https://psk.mist.com/xxxxxx)"
  name: Orgs Psk Portals
- name: Orgs RF Templates
- name: Orgs SDK Clients
- name: Orgs SDK Templates
- description: "Security Policy is designed to audit / catch discripancies between\
    \ \u201Cwhat\u2019s intended to be running\u201D versus \u201Cwhat\u2019s actually\
    \ running\u201D in a network. Many big organizations have separated Security and\
    \ IT team (for good reasons). Each site can be assigned a security policy. Whenever\
    \ an AP is provisioned, the configuration will be checked against the security\
    \ policy. Any violations will be flagged in [Device Config History](/#operation/searchSiteDeviceConfigHistory)\
    \ where you can search for the when and where the violation occurs."
  name: Orgs SecPolicies
- name: Orgs Services
- name: Orgs Service Policies
- name: Orgs Setting
- name: Orgs Sitegroups
- name: Orgs Sites
- description: Site template is intended to be applied to a Site. The items in site
    setting which should be shared for all device types.
  name: Orgs Site Templates
- name: Orgs SLEs
- name: Orgs SSO Roles
- name: Orgs SSO
- name: Orgs Stats
- name: Orgs Subscriptions
- name: Orgs Templates
- name: Orgs Tickets
- name: Orgs Tunnels
- name: Orgs Tunnels Stats
- name: Orgs VPNs
- name: Orgs Webhooks
- name: Orgs Wlans
- name: Orgs WxRules
- name: Orgs WxTags
- name: Orgs WxTunnels
- description: A site represents a project, a deployment. For MSP, it can be as small
    as a coffee shop or a five-star 600-room hotel. A site contains a set of Maps,
    Wlans, Policies, Zones.
  name: Sites
- name: Sites Alarms
- description: Applications contains a list of applications users are interested in
    monitoring / routing / policying
  name: Sites Applications
- name: Sites Anomaly
- name: Sites Asset Filters
- name: Sites Assets
- name: Sites Beacons
- name: Sites Calls
- name: Sites Clients - Wan
- name: Sites Clients - Wired
- name: Sites Clients - Wireless
- description: 'Mist provides many ways (device-type specific template, site template,
    device profile, per-device) to configure devices for different kind of scenarios.

    The precedence goes from most specific to least specific

    Device > Device Profile > RFTemplate (for AP only) > DeviceType-specific Template
    > Site Template > Site Setting'
  name: Sites Devices
- name: Sites Devices - Wireless
- description: API Call for 3rd party devices
  name: Sites Devices Others
- name: Sites Devices - Wired
- name: Sites Devices - Wired Virtual Chassis
- name: Sites Devices - WAN
- name: Sites Devices - WAN HA
- name: Sites Devices Stats
- name: Sites Devices Upgrades
- name: Sites Devices Utilities
- name: Sites Device Profiles
- name: Sites Events
- description: 'EVPN allows an alternative but more efficient LAN architecture utilizing
    VxLAN / MP-BGP - separating control plane (MAC / IP Learning) from forwarding
    plane.

    In our implementation, following the steps to deploy EVPN topologies in a Site '
  name: Sites EVPN Topologies
- name: Sites Guests
- name: Sites Insights
- name: Sites Licenses
- name: Sites Location
- name: Sites Maps
- name: Sites Maps Auto-orientation
- name: Sites Maps Auto-placement
- name: Sites MxEdges
- name: Sites MxTunnels
- name: Sites Networks
- name: Sites Pcaps
- name: Sites Psks
- name: Sites Rfdiags
- name: Sites Rogues
- name: Sites RRM
- name: Sites Rssizones
- name: Sites Services
- name: Sites Service Policies
- name: Sites Setting
- name: Sites Skyatp
- name: Sites SLEs
- name: Sites Stats
- name: Sites Subscriptions
- name: Sites Synthetic Tests
- name: Sites UI Settings
- name: Sites vBeacons
- name: Sites VPNs
- name: Sites Webhooks
- name: Sites Wlans
- name: Sites WxRules
- name: Sites WxTags
- name: Sites WxTunnels
- name: Sites Zones
- name: Constants
- name: Self
- name: Account
- name: Webhook Samples
paths:
  /webhook_example/_alarm_:
    post:
      description: 'Webhook sample for `alarm` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages'
      operationId: alarms
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - aps:
                    - string
                    bssids:
                    - string
                    count: 0
                    event_id: a7a26ff2-e851-45b6-9634-d595f45458b7
                    for_site: true
                    id: 489f6eca-6276-4993-bfeb-c3cbbbba6f08
                    last_seen: 0
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    ssids:
                    - string
                    timestamp: 0
                    type: string
                    update: true
                  topic: alarms
            schema:
              $ref: ./components/schemas/webhook_alarms.yaml
        description: "**N.B.**: Fields like `aps`, `bssids`, `ssids` are event specific.\
          \ They are relevant to this event type ( rogue-ap-detected). For a different\
          \ event type, different fields may be sent. These don\u2019t contain all\
          \ affected entities and are representative samples of entities (capped at\
          \ 10). For marvis action related events, we expose `details` to include\
          \ more event specific details.\n\nEvents specific fields for other alarm\
          \ event type can be found with API https://api.mist.com/api/v1/const/alarm_defs,\
          \ under \u201Cfields\u201D array of /alarm_defs response object."
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: alarms
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_asset_raw_:
    post:
      description: 'Webhook sample for `asset_raw` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages


        **will be deprecated after 03/31/2024**'
      operationId: assetRaw
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - asset_id: b4695157-0d1d-4da0-8f9e-5c53149389e4
                    beam: 0
                    device_id: 3bafab7b-4400-4bcf-8e6e-09f954699940
                    ibeacon_major: 0
                    ibeacon_minor: 0
                    ibeacon_uuid: 1f89bc00-d0af-481b-82fe-a6629259a39f
                    mac: string
                    map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                    mfg_company_id: 0
                    mfg_data: string
                    rssi: 0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                  topic: asset-raw
            schema:
              $ref: ./components/schemas/webhook_asset_raw.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: assetRaw
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_audit_:
    post:
      description: 'Webhook sample for `audit` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: audits
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - admin_name: string
                    device_id: 3bafab7b-4400-4bcf-8e6e-09f954699940
                    id: 488f6eca-6276-4993-bfeb-d3cbbbba6f08
                    message: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    src_ip: string
                    timestamp: 0
                  topic: audits
            schema:
              $ref: ./components/schemas/webhook_audits.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: audits
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_client_join_:
    post:
      description: 'Webhook sample for `client_join` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: clientJoin
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    band: string
                    bssid: string
                    connect: 0
                    connect_float: 0
                    mac: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    rssi: 0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    ssid: string
                    timestamp: 0
                    version: 0
                    wlan_id: 5028e92b-fc59-4056-91d1-ea4b4ca1617a
                  topic: client-join
            schema:
              $ref: ./components/schemas/webhook_client_join.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: clientJoin
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_client_sessions_:
    post:
      description: 'Webhook sample for `client_sessions` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: clientSessions
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    band: string
                    bssid: string
                    client_family: string
                    client_manufacture: string
                    client_model: string
                    client_os: string
                    connect: 0
                    connect_float: 0
                    disconnect: 0
                    disconnect_float: 0
                    duration: 0
                    mac: string
                    next_ap: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    rssi: 0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    ssid: string
                    termination_reason: 0
                    timestamp: 0
                    version: 0
                    wlan_id: 5028e92b-fc59-4056-91d1-ea4b4ca1617a
                  topic: client-sessions
            schema:
              $ref: ./components/schemas/webhook_client_sessions.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
      summary: clientSessions
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_device_events_:
    post:
      description: 'Webhook sample for `device_events` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: deviceEvents
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    audit_id: 78c04fa6-cfb4-46a0-9aa5-3681ba4f3897
                    device_name: string
                    device_type: ap
                    ev_type: notice
                    mac: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    reason: string
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    text: string
                    timestamp: 0
                    type: string
                  topic: device-events
            schema:
              $ref: ./components/schemas/webhook_device_events.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: deviceEvents
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_device_updowns_:
    post:
      description: 'Webhook sample for `device_updowns` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: deviceUpDown
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - ap: string
                    ap_name: string
                    for_site: true
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                    timestamp: 0
                    type: string
                  topic: device-updowns
            schema:
              $ref: ./components/schemas/webhook_device_updowns.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: deviceUpDown
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_discovered_raw_rssi_:
    post:
      description: 'Webhook sample for `discovered-raw-rssi` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: discovered-raw-rssi
      requestBody:
        content:
          application/json:
            examples:
              Example 1:
                value:
                  events:
                  - ap_loc:
                    - 0
                    beam: 0
                    device_id: 3bafab7b-4400-4bcf-8e6e-09f954699940
                    ibeacon_major: 0
                    ibeacon_minor: 0
                    ibeacon_uuid: 1f89bc00-d0af-481b-82fe-a6629259a39f
                    is_asset: true
                    mac: string
                    map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                    mfg_company_id: string
                    mfg_data: string
                    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                    rssi: 0
                    service_packets:
                    - service_data: string
                      service_uuid: 7138cc00-c611-4dec-a05e-5c4b1cae13c0
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                  topic: string
            schema:
              $ref: ./components/schemas/webhook_discovered_raw_rssi.yaml
        description: ''
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: discovered-raw-rssi
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_location_:
    post:
      description: 'Webhook sample for `location` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: location
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - battery_voltage: 0
                    eddystone_uid_instance: string
                    eddystone_uid_namespace: string
                    eddystone_url_url: string
                    ibeacon_major: 0
                    ibeacon_minor: 0
                    ibeacon_uuid: 1f89bc00-d0af-481b-82fe-a6629259a39f
                    id: 487f6eca-6276-4993-bfeb-e3cbbbba6f08
                    mac: string
                    map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                    mfg_company_id: 0
                    mfg_data: string
                    name: string
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                    type: string
                    x: 0
                    y: 0
                  topic: location
            schema:
              $ref: ./components/schemas/webhook_location.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: location
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_occupancy_alerts_:
    post:
      description: 'Webhook sample for `occupancy_alerts` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: occupancyAlerts
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - alert_events:
                    - current_occupancy: 0
                      map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                      occupancy_limit: 0
                      org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
                      timestamp: 0
                      type: COMPLIANCE-VIOLATION
                      zone_id: 4495020a-236f-46e0-9453-e3f9cc6476f4
                      zone_name: string
                    for_site: true
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    site_name: string
                  topic: occupancy-alerts
            schema:
              $ref: ./components/schemas/webhook_occupancy_alerts.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: occupancyAlerts
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_ping_:
    post:
      description: 'Webhook sample for `ping` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: ping
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - id: 487f6eca-6276-4993-bfeb-f3cbbbba6f08
                    name: string
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                  topic: ping
            schema:
              $ref: ./components/schemas/webhook_ping.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: ping
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_sdkclient_scan_data:
    post:
      description: 'Webhook sample for `sdkclient_scan_data` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: sdkclientScanData
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - connection_ap: 5c5b352f587e
                    connection_band: '2.4'
                    connection_bssid: 5c5b352b51b4
                    connection_channel: 11
                    connection_rssi: -87
                    last_seen: 1592333828
                    mac: 70ef0071535f
                    scan_data:
                    - ap: 5c5b352f587e
                      band: '2.4'
                      bssid: 5c5b352b51b4
                      channel: 11
                      rssi: -87
                      ssid: mist-wifi
                      timestamp: 1592333828
                    - ap: 5c5b352f587e
                      band: '5'
                      bssid: 5c5b352b51b8
                      channel: 36
                      rssi: -75
                      ssid: mist-wifi
                      timestamp: 1592333828
                    site_id: d761985e-49b1-4506-88e9-e0368a05c301
                  topic: sdkclient-scan-data
            schema:
              $ref: ./components/schemas/webhook_sdkclient-scan-data.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: sdkclientScanData
      tags:
      - Webhook Samples
      - Monitor
  /webhook_example/_zone_:
    post:
      description: 'Webhook sample for `zone` topic


        **Note**: The server host will be your own server FQDN where the Mist Cloud
        is sending the webhook messages

        '
      operationId: zone
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  events:
                  - asset_id: b4695157-0d1d-4da0-8f9e-5c53149389e4
                    id: 485f6eca-6276-4993-bfeb-54cbbbba6f08
                    mac: string
                    map_id: 09d2b626-2e4e-45ef-a3c4-e6aeb6c83db1
                    name: string
                    site_id: 72771e6a-6f5e-4de4-a5b9-1266c4197811
                    timestamp: 0
                    trigger: enter
                    type: string
                    zone_id: 4495020a-236f-46e0-9453-e3f9cc6476f4
                  topic: zone
            schema:
              $ref: ./components/schemas/webhook_zone.yaml
      responses:
        '200':
          $ref: '#/components/responses/OK'
      summary: zone
      tags:
      - Webhook Samples
      - Monitor
components:
  parameters: {}
  responses:
    OK:
      content:
        application/json:
          schema:
            type: object
      description: OK
x-tagGroups:
- name: Account
  tags:
  - Login
  - Login With OAuth2
  - API Token
  - Self
- name: Sites
  tags:
  - Sites
  - Sites Alarms
  - Sites Applications
  - Sites Anomaly
  - Sites Asset Filters
  - Sites Assets
  - Sites Beacons
  - Sites Calls
  - Sites Clients - Wan
  - Sites Clients - Wired
  - Sites Clients - Wireless
  - Sites Devices
  - Sites Devices - Wireless
  - Sites Devices Others
  - Sites Devices - Wired
  - Sites Devices - Wired Virtual Chassis
  - Sites Devices - WAN
  - Sites Devices - WAN HA
  - Sites Devices Upgrades
  - Sites Devices Utilities
  - Sites Devices Stats
  - Sites Device Profiles
  - Sites Events
  - Sites EVPN Topologies
  - Sites Guests
  - Sites Insights
  - Sites Licenses
  - Sites Location
  - Sites Maps
  - Sites Maps Auto-orientation
  - Sites Maps Auto-placement
  - Sites MxEdges
  - Sites MxTunnels
  - Sites Networks
  - Sites Pcaps
  - Sites Psks
  - Sites Rfdiags
  - Sites Rogues
  - Sites RRM
  - Sites Rssizones
  - Sites Services
  - Sites Service Policies
  - Sites Setting
  - Sites Skyatp
  - Sites SLEs
  - Sites Stats
  - Sites Subscriptions
  - Sites Synthetic Tests
  - Sites UI Settings
  - Sites vBeacons
  - Sites VPNs
  - Sites Webhooks
  - Sites Wlans
  - Sites WxRules
  - Sites WxTags
  - Sites WxTunnels
  - Sites Zones
- name: Orgs
  tags:
  - Orgs
  - Orgs 128T
  - Orgs Admins
  - Orgs Alarms
  - Orgs Alarm Templates
  - Orgs AP Templates
  - Orgs API Tokens
  - Orgs Assets
  - Orgs Asset Filters
  - Orgs Calls
  - Orgs Cert
  - Orgs Clients - Wan
  - Orgs Clients - Wired
  - Orgs Clients - Wireless
  - Orgs CRL
  - Orgs Devices
  - Orgs Devices Others
  - Orgs Devices Stats
  - Orgs Devices Upgrades
  - Orgs Devices Zscaler
  - Orgs Device Profiles
  - Orgs EVPN Topologies
  - Orgs Gateway Templates
  - Orgs Guests
  - Orgs Inventory
  - Orgs JSE
  - Orgs JSI
  - Orgs Licenses
  - Orgs Logs
  - Orgs Maps
  - Orgs Marvis
  - Orgs MxClusters
  - Orgs MxEdges
  - Orgs MxTunnels
  - Orgs NAC Rules
  - Orgs NAC Tags
  - Orgs Network Templates
  - Orgs Networks
  - Orgs OAuth
  - Orgs Premium Analytics
  - Orgs Psks
  - Orgs Psk Portals
  - Orgs RF Templates
  - Orgs SDK Clients
  - Orgs SDK Templates
  - Orgs SecPolicies
  - Orgs Services
  - Orgs Service Policies
  - Orgs Setting
  - Orgs Sitegroups
  - Orgs Sites
  - Orgs Site Templates
  - Orgs SLEs
  - Orgs SSO Roles
  - Orgs SSO
  - Orgs Stats
  - Orgs Subscriptions
  - Orgs Templates
  - Orgs Tickets
  - Orgs Tunnels
  - Orgs Tunnels Stats
  - Orgs VPNs
  - Orgs Webhooks
  - Orgs Wlans
  - Orgs WxRules
  - Orgs WxTags
  - Orgs WxTunnels
- name: MSPs
  tags:
  - Msps
  - Msps Admins
  - Msps Inventory
  - Msps Logo
  - Msps Invites
  - Msps Logs
  - Msps Licenses
  - Msps Marvis
  - Msps Org Groups
  - Msps Orgs
  - Msps SLEs
  - Msps SSO Roles
  - Msps SSO
  - Msps Stats
  - Msps Tickets
- name: Installer
  tags:
  - Installer
- name: Webhook Samples
  tags:
  - Webhook Samples
- name: Constants
  tags:
  - Constants
- name: Others
  tags:
  - Admin
  - Mobile
