openapi: 3.0.1
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2306.1.6**

    >

    > Date: **June 21, 2023**


    ---


    #### Available Documentation

    * [Postman](https://documenter.getpostman.com/view/224925/SzYgQufe)

    * [Open API](https://doc.mist-lab.fr/)


    ---


    #### Useful links

    * [Mist Homepage](https://www.mist.com)

    * [Mist Documentation](https://www.mist.com/documentation)

    * [Official API Documentation](https://api.mist.com/api/v1/docs/Home) (Mist account
    required)

    * [Mist Blog](https://www.mist.com/news/?md_post_type=post)

    * [Mist Updates](https://www.mist.com/documentation/category/product-updates/)'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist API
  version: 2306.1.6
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Europe 01
  url: https://api.eu.mist.com
security:
- apiToken: []
- basicAuth: []
tags:
- name: Authentication
- name: Monitor
- name: Operational
- name: Login
- description: A Mist account can be linked to OAuth2 providers:\n1. First, login
    with your Mist account\n2. Obtain the Authorization URL for Linking 1. in JSON
    response, more usable for developers. Simply don\'t specify the forward parameter
    when obtaining the authorization URL 2. or as GET parameter, for UI where the
    user flow can be continued. Specify the landing page/url of your choice 3. Obtain
    the authorizaiton code by clicking / going through Authorization URL Link Mist
    Account against OAuth2 Provider by using the authorization code
  name: Login With OAuth2
- description: "Like many other API providers, it\u2019s also possible to generate\
    \ API Tokens to be used (in HTTP Header) for authentication. An API token ties\
    \ to a Admin with equal or less privileges.\n\nNotes:\n* an API token generated\
    \ for a specific admin has the same privilege as the user\n* an API token will\
    \ be automatically removed if not used for > 90 days\n* SSO admins cannot generate\
    \ these API tokens. Refer Org level API tokens (/api/v1/docs/Org#api-token) which\
    \ can have privileges of a specific Org/Site for more information."
  name: API Token
- description: "In a typical enterprise, a separate group of people, Installers, are\
    \ responsible for install new devices. May it be a new installation (e.g. new\
    \ stores), a replacement installation (e.g. replacing Cisco APs with Mist APs),\
    \ or addition (e.g. adding new APs for better coverage). Instead of granting them\
    \ Admin/Write privilege, it's more desirable to grant them minimum privileges\
    \ to do the initial provisioning so they cannot read sensible information (e.g.\
    \ PSK of a WLAN), or change configs of running APs.\nAt a high level, Installer\
    \ APs try to achieve the following:\n1. identifying a device by MAC (that\u2019\
    s what they see)\n2. they can only touch configurations of the devices they\u2019\
    re installing\n3. allow the following configurations: * name * site assignment\
    \ * device  profile assignment * map and location (x/y) assignment * claim (if\
    \ not already in the inventory) * replace existing device with the device being\
    \ installed\n\n* Grace Period *\nGrace period provides a dynamic way to limit\
    \ what devices / sites   installer can work on. Generally installers work on recent\
    \ deployments -  bringing up new sites, add newly claimed devices to new / existing\
    \ sites. They  make mistakes, too, and may need to further tweak some of the parameters.\
    \   Default grace period is 7 days and can be set from 1 day to 365 days."
  name: Installer
- name: Admin
- name: Mobile
- description: MSP (Managed Service Provider) contains multiple Organizations.
  name: Msps
- name: Msps Admins
- name: Msps Inventory
- name: Msps Invites
- name: Msps Logo
- name: Msps Logs
- name: Msps Licenses
- name: Msps Marvis
- name: Msps Org Groups
- name: Msps Orgs
- name: Msps SLEs
- name: Msps SSO Roles
- name: Msps SSO
- name: Msps Stats
- name: Msps Tickets
- description: An organization usually represents a customer - which has inventories,
    licenses. An Organization can contain multiple sites. A site usually represents
    a deployment at the same location (a campus, an office).
  name: Orgs
- name: Orgs 128T
- name: Orgs Admins
- description: Alarms are triggered based on certain events. Alarms could be configured
    using an Alarm Template.
  name: Orgs Alarms
- description: An Alarm Template is a set of Alarm Rules that could be applied to
    one or more sites (while each site can only pick one Alarm Template), or to the
    whole org.
  name: Orgs Alarm Templates
- name: Orgs AP Templates
- name: Orgs API Tokens
- name: Orgs Assets
- name: Orgs Asset Filters
- name: Orgs Calls
- name: Orgs Cert
- name: Orgs Clients - Wan
- name: Orgs Clients - Wired
- name: Orgs Clients - Wireless
- name: Orgs CRL
- description: 'While Templates / RF Templates / Network Templates / Gateway Templates
    provides powerful ways to control how a Device\''s configuration is derived for
    a Site. There are cases where you\''d like another level of control at the Org
    Level.

    A Device Profile contains a subset of Device\''s configurations you\''d like a
    device to have. It will be merged at runtime when we\''re provisioning an AP.'
  name: Orgs Device Profiles
- name: Orgs Devices
- description: 'EVPN allows an alternative but more efficient LAN architecture utilizing
    VxLAN / MP-BGP - separating control plane (MAC / IP Learning) from forwarding
    plane.

    In our implementation, following the steps to deploy EVPN topologies in a Site'
  name: Orgs EVPN Topologies
- description: API Call for 3rd party devices
  name: Orgs Devices Others
- name: Orgs Devices Stats
- name: Orgs Devices Upgrades
- description: "In Zscaler UI \n 1. add Partner Integration at https://admin.zscalerbeta.net/#administration/partner-integration\
    \ \n 2. Add Partner Administrator Role at https://admin.zscalerbeta.net/#administration/role-management\
    \ - Name: Mist - Access: Full \n 3. add Partner Admin at https://admin.zscalerbeta.net/#administration/admin-management\
    \ with - Login ID: john - email: john@abc.com \n 4. Find the cloud name for ZIA\
    \ https://help.zscaler.com/zia/what-my-cloud-name-zia\n"
  name: Orgs Devices Zscaler
- description: Gateway Template is applied to a site for gateway(s) in a site.
  name: Orgs Gateway Templates
- name: Orgs Guests
- name: Orgs Inventory
- name: Orgs JSE
- description: "Juniper Support Insight is a free service provided to all Mist customers.\
    \ You can adopt your devices via a few lines CLI comands. Allowing you to \n*\
    \ get some basic information about the adopted devices \n* web shell into device\
    \ (write privilege required) \n* upgrade (write privilege required)"
  name: Orgs JSI
- name: Orgs Licenses
- name: Orgs Logs
- name: Orgs Marvis
- name: Orgs Maps
- name: Orgs MxClusters
- name: Orgs MxEdges
- name: Orgs MxTunnels
- description: 'nactags are the building blocks to compose nacrules.

    They can either appear in the "matching" / "not_matching" sections of a nacrule,
    in which case they play the role of classifiers, or they could appear in the "apply_tags"
    section of the of a nacrule, in which case they influence the result.

    When the "type" field of nactag is "match", it can be used as the classfier of
    a nacrule. "match" field specifies the attribute name and "values" field specifies
    the list of attribute values to match on. When multiple values are specified,
    its treated as an OR condition between those values.

    When the "type" field of nactag is NOT "match", it can be used as the result of
    a nacrule. "type" field identifies the action to take and the corresponding field
    would provide any associated parameters to that action.'
  name: Orgs NAC Tags
- name: Orgs NAC Rules
- description: 'Network template is intended to be applied to a Site. It works like
    a blueprint of the network of the site.

    All Site Settings can go into Network Templates. See Site:Site Setting for schema

    Moreover, this can further be overwriten by individual Site Setting'
  name: Orgs Network Templates
- name: Orgs Networks
- name: Orgs OAuth
- name: Orgs Premium Analytics
- name: Orgs Psks
- description: "PSK Self-Service Portals are for \n  1. **WIFI users** who want to\
    \ connect to a WLAN with personal PSK, they\u2019re told to connect to a URL where\
    \ they can login (likely through company\u2019s SSO) and get the WIFI Name / Passphrase\
    \ - required input fields name, email so we can generate PSK \n  2. **PSK Admins**\
    \ (they don\u2019t have access to normal Network Admin Portal)\nWhen a PSK portal\
    \ is created, an unique URL will be generated (e.g. https://psk.mist.com/xxxxxx)"
  name: Orgs Psk Portals
- name: Orgs RF Templates
- name: Orgs SDK Clients
- name: Orgs SDK Templates
- description: "Security Policy is designed to audit / catch discripancies between\
    \ \u201Cwhat\u2019s intended to be running\u201D versus \u201Cwhat\u2019s actually\
    \ running\u201D in a network. Many big organizations have separated Security and\
    \ IT team (for good reasons). Each site can be assigned a security policy. Whenever\
    \ an AP is provisioned, the configuration will be checked against the security\
    \ policy. Any violations will be flagged in [Device Config History](/#operation/searchSiteDeviceConfigHistory)\
    \ where you can search for the when and where the violation occurs."
  name: Orgs SecPolicies
- name: Orgs Services
- name: Orgs Service Policies
- name: Orgs Setting
- name: Orgs Sitegroups
- name: Orgs Sites
- description: Site template is intended to be applied to a Site. The items in site
    setting which should be shared for all device types.
  name: Orgs Site Templates
- name: Orgs SLEs
- name: Orgs SSO Roles
- name: Orgs SSO
- name: Orgs Stats
- name: Orgs Subscriptions
- name: Orgs Templates
- name: Orgs Tickets
- name: Orgs Tunnels
- name: Orgs Tunnels Stats
- name: Orgs VPNs
- name: Orgs Webhooks
- name: Orgs Wlans
- name: Orgs WxRules
- name: Orgs WxTags
- name: Orgs WxTunnels
- description: A site represents a project, a deployment. For MSP, it can be as small
    as a coffee shop or a five-star 600-room hotel. A site contains a set of Maps,
    Wlans, Policies, Zones.
  name: Sites
- name: Sites Alarms
- description: Applications contains a list of applications users are interested in
    monitoring / routing / policying
  name: Sites Applications
- name: Sites Anomaly
- name: Sites Asset Filters
- name: Sites Assets
- name: Sites Beacons
- name: Sites Calls
- name: Sites Clients - Wan
- name: Sites Clients - Wired
- name: Sites Clients - Wireless
- description: 'Mist provides many ways (device-type specific template, site template,
    device profile, per-device) to configure devices for different kind of scenarios.

    The precedence goes from most specific to least specific

    Device > Device Profile > RFTemplate (for AP only) > DeviceType-specific Template
    > Site Template > Site Setting'
  name: Sites Devices
- name: Sites Devices - Wireless
- description: API Call for 3rd party devices
  name: Sites Devices Others
- name: Sites Devices - Wired
- name: Sites Devices - Wired Virtual Chassis
- name: Sites Devices - WAN
- name: Sites Devices - WAN HA
- name: Sites Devices Stats
- name: Sites Devices Upgrades
- name: Sites Devices Utilities
- name: Sites Device Profiles
- name: Sites Events
- description: 'EVPN allows an alternative but more efficient LAN architecture utilizing
    VxLAN / MP-BGP - separating control plane (MAC / IP Learning) from forwarding
    plane.

    In our implementation, following the steps to deploy EVPN topologies in a Site '
  name: Sites EVPN Topologies
- name: Sites Guests
- name: Sites Insights
- name: Sites Licenses
- name: Sites Location
- name: Sites Maps
- name: Sites Maps Auto-orientation
- name: Sites Maps Auto-placement
- name: Sites MxEdges
- name: Sites MxTunnels
- name: Sites Networks
- name: Sites Pcaps
- name: Sites Psks
- name: Sites Rfdiags
- name: Sites Rogues
- name: Sites RRM
- name: Sites Rssizones
- name: Sites Services
- name: Sites Service Policies
- name: Sites Setting
- name: Sites Skyatp
- name: Sites SLEs
- name: Sites Stats
- name: Sites Subscriptions
- name: Sites Synthetic Tests
- name: Sites UI Settings
- name: Sites vBeacons
- name: Sites VPNs
- name: Sites Webhooks
- name: Sites Wlans
- name: Sites WxRules
- name: Sites WxTags
- name: Sites WxTunnels
- name: Sites Zones
- name: Constants
- name: Self
- name: Account
- name: Webhook Samples
paths:
  /api/v1/self/logs:
    get:
      description: 'Get List of change logs across all Orgs for current admin

        Audit logs records all administrative activities done by current admin across
        all orgs'
      operationId: listSelfAuditLogs
      parameters:
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    end: 1428954000
                    limit: 100
                    page: 1
                    results:
                    - admin_id: 72bfa2bd-e58a-4670-9d20-a1468f7a6f58
                      admin_name: test@mistsys.com
                      after:
                        auth:
                          type: open
                      before:
                        auth:
                          type: psk
                      id: c6f9347b-b0a4-4a23-b927-fa9249f2ffb2
                      message: Update WLAN "Corporate"
                      org_id: 423f6eca-6276-4994-bfeb-53cbbbba6f04
                      site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                      timestamp: 1431382121
                    start: 1428939600
                    total: 135
              schema:
                properties:
                  end:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  results:
                    items:
                      properties:
                        admin_id:
                          format: uuid
                          type: string
                        admin_name:
                          type: string
                        after:
                          description: field values after the change
                          properties:
                            auth:
                              properties:
                                type:
                                  type: string
                              required:
                              - type
                              type: object
                          required:
                          - auth
                          type: object
                        before:
                          description: field values prior to the change
                          properties:
                            auth:
                              properties:
                                type:
                                  type: string
                              required:
                              - type
                              type: object
                          required:
                          - auth
                          type: object
                        for_site:
                          readOnly: true
                          type: boolean
                        id:
                          format: uuid
                          type: string
                        message:
                          type: string
                        org_id:
                          format: uuid
                          type: string
                        site_id:
                          format: uuid
                          type: string
                        timestamp:
                          type: number
                      required:
                      - admin_id
                      - admin_name
                      - id
                      - message
                      - org_id
                      - site_id
                      - timestamp
                      type: object
                    minItems: 1
                    type: array
                    uniqueItems: true
                  start:
                    type: integer
                  total:
                    type: integer
                required:
                - end
                - limit
                - page
                - results
                - start
                - total
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: listSelfAuditLogs
      tags:
      - Self
      - Monitor
  /api/v1/invite/verify/{token}:
    parameters:
    - $ref: '#/components/parameters/token'
    post:
      description: '**Note**: another call to ```GET /api/v1/self``` is required to
        see the new set of privileges'
      operationId: verifyAdminInvite
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                invalid secret:
                  value:
                    detail: invalid secret
                invite created by self:
                  value:
                    detail: invite created by self
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not Found
      summary: verifyAdminInvite
      tags:
      - Admin
      - Operational
  /api/v1/mobile/verify/{secret}:
    parameters:
    - $ref: '#/components/parameters/secret'
    post:
      description: Verify secret
      operationId: activateSdkInvite
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  device_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
            schema:
              $ref: ./components/schemas/Model_object_device_id.yaml
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    name: Macy's
                    org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                    secret: device-specific-secret
              schema:
                properties:
                  name:
                    type: string
                  org_id:
                    format: uuid
                    type: string
                  secret:
                    type: string
                required:
                - name
                - org_id
                - secret
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: activateSdkInvite
      tags:
      - Mobile
      - Operational
  /api/v1/register:
    post:
      description: 'Register a new admin and his/her org

        An email will also be sent to the user with a link to https://manage.mist.com/verify/register?token=:token'
      operationId: registerNewAdmin
      requestBody:
        content:
          application/json:
            schema:
              properties:
                account_only:
                  default: false
                  description: skip creating initial setup if true
                  type: boolean
                allow_mist:
                  default: false
                  description: whether to allow Mist to look at this org
                  type: boolean
                email:
                  type: string
                first_name:
                  type: string
                invite_code:
                  description: required initially
                  type: string
                last_name:
                  type: string
                org_name:
                  type: string
                password:
                  type: string
                recaptcha:
                  type: string
                referer_invite_token:
                  description: the invite token to apply after account creation
                  type: string
                return_to:
                  description: the url the user should be redirected back to
                  type: string
              required:
              - email
              - password
              - first_name
              - last_name
              - org_name
              - recaptcha
              type: object
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: registerNewAdmin
      tags:
      - Admin
      - Operational
  /api/v1/register/verify/{token}:
    parameters:
    - $ref: '#/components/parameters/token'
    post:
      description: Verify registration
      operationId: verifyRegistration
      responses:
        '200':
          content:
            application/json:
              examples:
                Response if successful:
                  value:
                    return_to: http://mist.zendesk.com/hc/quickstart.pdf
                Response if successful but failed to apply the invitation automatically:
                  value:
                    detail: password policy not met
                    invite_not_applied: true
                    min_length: 8
              schema:
                properties:
                  detail:
                    type: string
                  invite_not_applied:
                    type: boolean
                  min_length:
                    type: integer
                  return_to:
                    type: string
                type: object
          description: OK
          headers:
            Set-Cookie:
              schema:
                example: csrftoken=vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx; expires=Tue,
                  15-Mar-2016 19:47:20 GMT; Max-Age=31449600; Path=/
                type: string
        '400':
          content:
            application/json:
              examples:
                already registered:
                  value:
                    detail: already registered
                verification expired:
                  value:
                    detail: expired
              schema:
                properties:
                  detail:
                    type: string
                required:
                - detail
                type: object
          description: Response if verification expired or already registered
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                required:
                - detail
                type: object
          description: Response if secret is invalid
      summary: verifyRegistration
      tags:
      - Admin
      - Operational
  /api/v1/self:
    delete:
      description: 'To delete ones account and every associated with it. The effects:


        the account would be deleted

        any orphaned Org (that only has this account as admin) will be deleted

        along with all data with Org (sites, wlans, devices) will be gone.'
      operationId: deleteSelf
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              examples:
                if any of the org to be deleted still has inventory:
                  value:
                    detail: inventory not empty
                    org_id: 424f6eca-7276-4993-bfeb-53cbbbba6f05
              schema:
                properties:
                  detail:
                    type: string
                  org_id:
                    format: uuid
                    type: string
                required:
                - detail
                - org_id
                type: object
          description: Bad Request
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: deleteSelf
      tags:
      - Self
      - Operational
    get:
      description: "Get \u2018whoami\u2019 and privileges (which org and which sites\
        \ I have access to)"
      operationId: getSelf
      responses:
        '200':
          $ref: '#/components/responses/Admin'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: getSelf
      tags:
      - Self
      - Operational
    put:
      description: update Account Information
      operationId: updateSelf
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  email: john.smith@mycorp.net
                  enable_two_factor: true
                  first_name: John
                  last_name: Smith
                  password: foryoureyesonly
                  persona: security
                  phone: '14081112222'
                  phone2: '14083334444'
            schema:
              $ref: ./components/schemas/Model_object_device_id.yaml
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/Admin'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: updateSelf
      tags:
      - Self
      - Operational
  /api/v1/self/apitokens:
    get:
      description: Get List of Current User API Tokens
      operationId: listApiTokens
      responses:
        '200':
          $ref: '#/components/responses/ApitokensArray'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: listApiTokens
      tags:
      - API Token
      - Operational
    post:
      description: 'Create API Token

        Note that the key is only available during creation time.'
      operationId: createApiToken
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
              type: object
      responses:
        '200':
          $ref: '#/components/responses/Apitoken'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: createApiToken
      tags:
      - API Token
      - Operational
  /api/v1/self/apitokens/{apitoken_id}:
    delete:
      description: Delete an API Token
      operationId: deleteApiToken
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: deleteApiToken
      tags:
      - API Token
      - Operational
    parameters:
    - in: path
      name: apitoken_id
      required: true
      schema:
        type: string
    put:
      description: Update API Token
      operationId: updateApiToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./components/schemas/Model_object_device_id.yaml
      responses:
        '200':
          $ref: '#/components/responses/Apitoken'
      summary: updateApiToken
      tags:
      - API Token
      - Operational
  /api/v1/self/subscriptions:
    get:
      description: Get List of all the subscriptions
      operationId: listAlarmSubscriptions
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    org_id:
                      format: uuid
                      type: string
                  required:
                  - org_id
                  type: object
                minItems: 1
                type: array
                uniqueItems: true
          description: OK
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: listAlarmSubscriptions
      tags:
      - Self
      - Operational
  /api/v1/self/update:
    post:
      description: 'Change Email

        We require the user to verify that they actually own the email address they
        intend to change it to.


        After the API call, the user will receive an email to the new email address
        with a link like https://manage.mist.com/verify/update?expire=:exp_time&email=:admin_email&token=:token


        Upon clicking the link, the user is provided with a login page to authenticate
        using existing credentials. After successful login, the email address of the
        user gets updated


        **Note**: The request parameter email can be used by UI to validate that the
        current session (if any) belongs to the admin or provide a login page (by
        pre-populating the email on login screen). UI can also use the request parameter
        expire to validate token expiry.'
      operationId: updateSelfEmail
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  email: new@mistsys.com
            schema:
              $ref: ./components/schemas/Model_object_device_id.yaml
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              examples:
                invalid email address:
                  value: {}
                new email address already exists:
                  value:
                    detail: email already existed
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: invalid email address or new email address already exists
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: updateSelfEmail
      tags:
      - Self
      - Operational
  /api/v1/self/update/verify/{token}:
    get:
      description: Verify Email change
      operationId: verifySelfEmail
      responses:
        '200':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: With correct verification, the email address of the user will
            be updated
        '400':
          content:
            application/json:
              examples:
                invalid or expired token:
                  value:
                    detail: invalid token
                new email address already exists:
                  value:
                    detail: email already existed
                request comes from authenticated users other than admin:
                  value:
                    detail: invalid token
              schema:
                properties:
                  detail:
                    type: string
                required:
                - detail
                type: object
          description: Bad Request
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: verifySelfEmail
      tags:
      - Self
      - Operational
    parameters:
    - $ref: '#/components/parameters/token'
components:
  parameters:
    secret:
      in: path
      name: secret
      required: true
      schema:
        type: string
    token:
      in: path
      name: token
      required: true
      schema:
        type: string
    duration:
      description: "For historical stats and/or logs where time range is needed, you\
        \ can specify the time range in a few different ways:\n  * ?start=1430000000&end=1430864000\t\
        specify the start / end\n  * ?end=1430864000&duration=1d\tspecify end time\
        \ and duration\n  * ?duration=1d\tspecify duration, end will be now() in seconds"
      in: query
      name: duration
      required: false
      schema:
        default: 1d
        example: 10m
        type: string
    end:
      in: query
      name: end
      schema:
        default: 0
        minimum: 0
        type: integer
    limit:
      in: query
      name: limit
      required: false
      schema:
        default: 100
        minimum: 0
        type: integer
    page:
      in: query
      name: page
      required: false
      schema:
        default: 1
        minimum: 1
        type: integer
    start:
      in: query
      name: start
      schema:
        default: 0
        minimum: 0
        type: integer
  responses:
    Admin:
      content:
        application/json:
          examples:
            example-1:
              value:
                admin_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                email: user@example.com
                first_name: string
                last_name: string
                privileges:
                - msp_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  msp_name: string
                  name: string
                  org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  org_name: string
                  orggroup_ids:
                  - b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  role: admin
                  scope: org
                  site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  sitegroup_ids:
                  - 6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9
          schema:
            $ref: ./components/schemas/Model_object_device_id.yaml
      description: OK
    Apitoken:
      content:
        application/json:
          examples:
            Org API Token:
              value:
                created_time: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                key: string
                last_used: 0
                name: string
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                privileges:
                - msp_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  msp_name: string
                  name: string
                  org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  org_name: string
                  orggroup_ids:
                  - b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  role: admin
                  scope: org
                  site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  sitegroup_ids:
                  - 6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9
            User API Token:
              value:
                created_time: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                key: string
                last_used: 0
                name: string
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
          schema:
            $ref: ./components/schemas/Model_object_device_id.yaml
      description: OK
    ApitokensArray:
      content:
        application/json:
          examples:
            Org API Tokens:
              value:
              - created_time: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                key: string
                last_used: 0
                name: string
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                privileges:
                - msp_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  msp_name: string
                  name: string
                  org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  org_name: string
                  orggroup_ids:
                  - b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  role: admin
                  scope: org
                  site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  sitegroup_ids:
                  - b069b358-4c97-5319-1f8c-7c5ca64d6ab1
            User API Tokens:
              value:
              - created_time: 0
                id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                key: string
                last_used: 0
                name: string
                org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
          schema:
            items:
              $ref: ./components/schemas/Model_object_device_id.yaml
            type: array
      description: OK
    OK:
      content:
        application/json:
          schema:
            type: object
      description: OK
x-tagGroups:
- name: Account
  tags:
  - Login
  - Login With OAuth2
  - API Token
  - Self
- name: Sites
  tags:
  - Sites
  - Sites Alarms
  - Sites Applications
  - Sites Anomaly
  - Sites Asset Filters
  - Sites Assets
  - Sites Beacons
  - Sites Calls
  - Sites Clients - Wan
  - Sites Clients - Wired
  - Sites Clients - Wireless
  - Sites Devices
  - Sites Devices - Wireless
  - Sites Devices Others
  - Sites Devices - Wired
  - Sites Devices - Wired Virtual Chassis
  - Sites Devices - WAN
  - Sites Devices - WAN HA
  - Sites Devices Upgrades
  - Sites Devices Utilities
  - Sites Devices Stats
  - Sites Device Profiles
  - Sites Events
  - Sites EVPN Topologies
  - Sites Guests
  - Sites Insights
  - Sites Licenses
  - Sites Location
  - Sites Maps
  - Sites Maps Auto-orientation
  - Sites Maps Auto-placement
  - Sites MxEdges
  - Sites MxTunnels
  - Sites Networks
  - Sites Pcaps
  - Sites Psks
  - Sites Rfdiags
  - Sites Rogues
  - Sites RRM
  - Sites Rssizones
  - Sites Services
  - Sites Service Policies
  - Sites Setting
  - Sites Skyatp
  - Sites SLEs
  - Sites Stats
  - Sites Subscriptions
  - Sites Synthetic Tests
  - Sites UI Settings
  - Sites vBeacons
  - Sites VPNs
  - Sites Webhooks
  - Sites Wlans
  - Sites WxRules
  - Sites WxTags
  - Sites WxTunnels
  - Sites Zones
- name: Orgs
  tags:
  - Orgs
  - Orgs 128T
  - Orgs Admins
  - Orgs Alarms
  - Orgs Alarm Templates
  - Orgs AP Templates
  - Orgs API Tokens
  - Orgs Assets
  - Orgs Asset Filters
  - Orgs Calls
  - Orgs Cert
  - Orgs Clients - Wan
  - Orgs Clients - Wired
  - Orgs Clients - Wireless
  - Orgs CRL
  - Orgs Devices
  - Orgs Devices Others
  - Orgs Devices Stats
  - Orgs Devices Upgrades
  - Orgs Devices Zscaler
  - Orgs Device Profiles
  - Orgs EVPN Topologies
  - Orgs Gateway Templates
  - Orgs Guests
  - Orgs Inventory
  - Orgs JSE
  - Orgs JSI
  - Orgs Licenses
  - Orgs Logs
  - Orgs Maps
  - Orgs Marvis
  - Orgs MxClusters
  - Orgs MxEdges
  - Orgs MxTunnels
  - Orgs NAC Rules
  - Orgs NAC Tags
  - Orgs Network Templates
  - Orgs Networks
  - Orgs OAuth
  - Orgs Premium Analytics
  - Orgs Psks
  - Orgs Psk Portals
  - Orgs RF Templates
  - Orgs SDK Clients
  - Orgs SDK Templates
  - Orgs SecPolicies
  - Orgs Services
  - Orgs Service Policies
  - Orgs Setting
  - Orgs Sitegroups
  - Orgs Sites
  - Orgs Site Templates
  - Orgs SLEs
  - Orgs SSO Roles
  - Orgs SSO
  - Orgs Stats
  - Orgs Subscriptions
  - Orgs Templates
  - Orgs Tickets
  - Orgs Tunnels
  - Orgs Tunnels Stats
  - Orgs VPNs
  - Orgs Webhooks
  - Orgs Wlans
  - Orgs WxRules
  - Orgs WxTags
  - Orgs WxTunnels
- name: MSPs
  tags:
  - Msps
  - Msps Admins
  - Msps Inventory
  - Msps Logo
  - Msps Invites
  - Msps Logs
  - Msps Licenses
  - Msps Marvis
  - Msps Org Groups
  - Msps Orgs
  - Msps SLEs
  - Msps SSO Roles
  - Msps SSO
  - Msps Stats
  - Msps Tickets
- name: Installer
  tags:
  - Installer
- name: Webhook Samples
  tags:
  - Webhook Samples
- name: Constants
  tags:
  - Constants
- name: Others
  tags:
  - Admin
  - Mobile
