openapi: 3.0.1
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2306.1.6**

    >

    > Date: **June 21, 2023**


    ---


    #### Available Documentation

    * [Postman](https://documenter.getpostman.com/view/224925/SzYgQufe)

    * [Open API](https://doc.mist-lab.fr/)


    ---


    #### Useful links

    * [Mist Homepage](https://www.mist.com)

    * [Mist Documentation](https://www.mist.com/documentation)

    * [Official API Documentation](https://api.mist.com/api/v1/docs/Home) (Mist account
    required)

    * [Mist Blog](https://www.mist.com/news/?md_post_type=post)

    * [Mist Updates](https://www.mist.com/documentation/category/product-updates/)'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist API
  version: 2306.1.6
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Europe 01
  url: https://api.eu.mist.com
security:
- apiToken: []
- basicAuth: []
tags:
- name: Authentication
- name: Login
- description: A Mist account can be linked to OAuth2 providers:\n1. First, login
    with your Mist account\n2. Obtain the Authorization URL for Linking 1. in JSON
    response, more usable for developers. Simply don\'t specify the forward parameter
    when obtaining the authorization URL 2. or as GET parameter, for UI where the
    user flow can be continued. Specify the landing page/url of your choice 3. Obtain
    the authorizaiton code by clicking / going through Authorization URL Link Mist
    Account against OAuth2 Provider by using the authorization code
  name: Login With OAuth2
- name: Self
paths:
  /api/v1/login:
    post:
      description: "Log in with email/password.\nWhen 2FA is enabled, there are two\
        \ ways to login:\n1. login with two_factor token (with Google Authenticator,\
        \ etc) \n2. login with email/password, generate the token, and use /login/two_factor\
        \ with the token"
      operationId: login
      requestBody:
        content:
          application/json:
            examples:
              with 2FA:
                value:
                  email: string
                  password: string
                  two_factor: string
              without 2FA:
                value:
                  email: string
                  password: string
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
                two_factor:
                  type: string
              required:
              - email
              - password
              type: object
      responses:
        '200':
          content:
            application/json:
              examples:
                2FA Required:
                  value:
                    email: test@mistsys.com
                    two_factor_passed: false
                    two_factor_required: true
                OK:
                  value: {}
              schema:
                properties:
                  email:
                    type: string
                  two_factor_passed:
                    type: boolean
                  two_factor_required:
                    type: boolean
                type: object
          description: Login Success
          headers:
            Set-Cookie:
              description: Session Cookie if login/password authentication is successful
              schema:
                example: csrftoken=vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx; expires=Tue,
                  15-Mar-2016 19:47:20 GMT; Max-Age=31449600; Path=/
                type: string
        '400':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    detail: sso admin login needs to be initiated by IdP
                    forward_url: https://my.sso/idp_sso_url
              schema:
                oneOf:
                - properties:
                    detail:
                      type: string
                    forward_url:
                      type: string
                  required:
                  - detail
                  type: object
          description: Login Failed
      summary: login
      tags:
      - Login
      - Authentication
  /api/v1/login/lookup:
    post:
      description: Login Lookup
      operationId: lookup
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  email: test@mistsys.com
            schema:
              $ref: ./components/schemas/Model_object_email.yaml
        description: Request Body
      responses:
        '200':
          content:
            application/json:
              examples:
                SSO user exists:
                  value:
                    sso_url: https://my.sso/idp_sso_url
                local user exists:
                  value: {}
              schema:
                properties:
                  sso_url:
                    type: string
                type: object
          description: account exists
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          description: user does not exist
      summary: lookup
      tags:
      - Login
      - Authentication
  /api/v1/login/oauth/{provider}:
    delete:
      description: Unlink OAuth2 Provider
      operationId: unlinkOAuth2Provider
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: unlinkOAuth2Provider
      tags:
      - Login With OAuth2
      - Authentication
    get:
      description: Obtain Authorization URL for Login
      operationId: getOAuth2AuthorizationUrlForLogin
      parameters:
      - in: query
        name: forward
        schema:
          example: http://manage.mist.com/oauth/callback.html
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    authorization_url: https://accounts.google.com/o/oauth2/v2/auth?.....
                    client_id: 173131512-mpbnju32.apps.googleusercontent.com
              schema:
                properties:
                  authorization_url:
                    type: string
                  client_id:
                    type: string
                required:
                - client_id
                - authorization_url
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: getOAuth2AuthorizationUrlForLogin
      tags:
      - Login With OAuth2
      - Authentication
    parameters:
    - in: path
      name: provider
      required: true
      schema:
        type: string
    post:
      description: Login via OAuth2
      operationId: loginOAuth2
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  code: 4/S9tegDeLkrYg0L9pWNXV4cgMVbbr3SR9t693A2kSHzw
            schema:
              properties:
                code:
                  type: string
              required:
              - code
              type: object
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: loginOAuth2
      tags:
      - Login With OAuth2
      - Authentication
  /api/v1/login/two_factor:
    post:
      description: Send 2FA Code
      operationId: twoFactor
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  two_factor: '123456'
            schema:
              properties:
                two_factor:
                  type: string
              required:
              - two_factor
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: two_factor code is correct
          headers: {}
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          description: "two_factor code is incorrect or the user hasn\u2019t login\
            \ yet"
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          description: "the user doesn\u2019t have 2FA enabled"
      summary: twoFactor
      tags:
      - Login
      - Authentication
  /api/v1/logout:
    post:
      description: Logout
      operationId: logout
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    forward_url: https://my.sso/custom_logout_url
              schema:
                properties:
                  forward_url:
                    description: if configured in SSO as custom_logout_url
                    type: string
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: logout
      tags:
      - Login
      - Authentication
  /api/v1/recover:
    post:
      description: 'Recover Password

        An email will also be sent to the user with a link to https://manage.mist.com/verify/recover?token=:token'
      operationId: recoverPassword
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  email: test@mistsys.com
                  recaptcha: see https://www.google.com/recaptcha/
            schema:
              properties:
                email:
                  type: string
                recaptcha:
                  type: string
              required:
              - email
              - recaptcha
              type: object
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: recoverPassword
      tags:
      - Self
      - Authentication
  /api/v1/recover/verify/{token}:
    parameters:
    - $ref: '#/components/parameters/token'
    post:
      description: 'Verify Recover Password

        With correct verification, the user will be authenticated. UI can then prompt
        for new password'
      operationId: verifyRecoverPasssword
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: verifyRecoverPasssword
      tags:
      - Self
      - Authentication
  /api/v1/self:
    delete:
      description: 'To delete ones account and every associated with it. The effects:


        the account would be deleted

        any orphaned Org (that only has this account as admin) will be deleted

        along with all data with Org (sites, wlans, devices) will be gone.'
      operationId: deleteSelf
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              examples:
                if any of the org to be deleted still has inventory:
                  value:
                    detail: inventory not empty
                    org_id: 424f6eca-7276-4993-bfeb-53cbbbba6f05
              schema:
                properties:
                  detail:
                    type: string
                  org_id:
                    format: uuid
                    type: string
                required:
                - detail
                - org_id
                type: object
          description: Bad Request
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: deleteSelf
      tags:
      - Self
      - Authentication
    get:
      description: "Get \u2018whoami\u2019 and privileges (which org and which sites\
        \ I have access to)"
      operationId: getSelf
      responses:
        '200':
          $ref: '#/components/responses/Admin'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: getSelf
      tags:
      - Self
      - Authentication
    put:
      description: update Account Information
      operationId: updateSelf
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  email: john.smith@mycorp.net
                  enable_two_factor: true
                  first_name: John
                  last_name: Smith
                  password: foryoureyesonly
                  persona: security
                  phone: '14081112222'
                  phone2: '14083334444'
            schema:
              $ref: ./components/schemas/admin.yaml
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/Admin'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: updateSelf
      tags:
      - Self
      - Authentication
  /api/v1/self/oauth/{provider}:
    get:
      description: Obtain Authorization URL for Linking
      operationId: getOAuth2UrlForLinking
      parameters:
      - in: query
        name: forward
        schema:
          example: http://manage.mist.com/oauth/callback.html
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    authorization_url: https://accounts.google.com/o/oauth2/v2/auth?.....
                    linked: false
              schema:
                properties:
                  authorization_url:
                    type: string
                  linked:
                    type: boolean
                required:
                - linked
                - authorization_url
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: getOAuth2UrlForLinking
      tags:
      - Login With OAuth2
      - Authentication
    parameters:
    - in: path
      name: provider
      required: true
      schema:
        type: string
    post:
      description: Link Mist account with an OAuth2 Provider
      operationId: linkOAuth2MistAccount
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  code: 4/S9tegDeLkrYg0L9pWNXV4cgMVbbr3SR9t693A2kSHzw
            schema:
              properties:
                code:
                  type: string
              required:
              - code
              type: object
        description: Request Body
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    action: oauth account linked
                    id: google-user-id
              schema:
                properties:
                  action:
                    type: string
                  id:
                    type: string
                required:
                - action
                - id
                type: object
          description: OK
        '400':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    error: access_denied
                    error_description: The resource owner or authorization server
                      denied the request.
              schema:
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                required:
                - error
                - error_description
                type: object
          description: Authorization Error
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: linkOAuth2MistAccount
      tags:
      - Login With OAuth2
      - Authentication
  /api/v1/self/subscriptions:
    get:
      description: Get List of all the subscriptions
      operationId: listAlarmSubscriptions
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    org_id:
                      format: uuid
                      type: string
                  required:
                  - org_id
                  type: object
                minItems: 1
                type: array
                uniqueItems: true
          description: OK
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: listAlarmSubscriptions
      tags:
      - Self
      - Authentication
  /api/v1/self/two_factor/token:
    get:
      description: Generate QR code for verification
      operationId: generateQrCodeForVerification
      parameters:
      - in: query
        name: by
        schema:
          default: qrcode
          enum:
          - qrcode
          type: string
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: generateQrCodeForVerification
      tags:
      - Self
      - Authentication
  /api/v1/self/two_factor/verify:
    post:
      description: "Verify Two-factor (OTP)\n\nTo verify two-factor authentication\
        \ by using a code generated by app (e.g. Google Authenticator, Authy) or by\
        \ SMS. Upon successful verification, the otp_verified will be set to true\
        \ if it hasn\u2019t already been."
      operationId: verifyTwoFactor
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  two_factor: '123456'
            schema:
              properties:
                two_factor:
                  type: string
              required:
              - two_factor
              type: object
        description: Request Body
      responses:
        '200':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Response when 2FA verification is successful
        '400':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: The API endpoint exists but its syntax/payload is incorrect,
            detail may be given
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: verifyTwoFactor
      tags:
      - Self
      - Authentication
  /api/v1/self/update:
    post:
      description: 'Change Email

        We require the user to verify that they actually own the email address they
        intend to change it to.


        After the API call, the user will receive an email to the new email address
        with a link like https://manage.mist.com/verify/update?expire=:exp_time&email=:admin_email&token=:token


        Upon clicking the link, the user is provided with a login page to authenticate
        using existing credentials. After successful login, the email address of the
        user gets updated


        **Note**: The request parameter email can be used by UI to validate that the
        current session (if any) belongs to the admin or provide a login page (by
        pre-populating the email on login screen). UI can also use the request parameter
        expire to validate token expiry.'
      operationId: updateSelfEmail
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  email: new@mistsys.com
            schema:
              $ref: ./components/schemas/Model_object_email.yaml
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          content:
            application/json:
              examples:
                invalid email address:
                  value: {}
                new email address already exists:
                  value:
                    detail: email already existed
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: invalid email address or new email address already exists
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: updateSelfEmail
      tags:
      - Self
      - Authentication
  /api/v1/self/update/verify/{token}:
    get:
      description: Verify Email change
      operationId: verifySelfEmail
      responses:
        '200':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: With correct verification, the email address of the user will
            be updated
        '400':
          content:
            application/json:
              examples:
                invalid or expired token:
                  value:
                    detail: invalid token
                new email address already exists:
                  value:
                    detail: email already existed
                request comes from authenticated users other than admin:
                  value:
                    detail: invalid token
              schema:
                properties:
                  detail:
                    type: string
                required:
                - detail
                type: object
          description: Bad Request
        '401':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Authentication credentials were not provided.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              examples:
                Permission Denied:
                  value:
                    detail: You do not have permission to perform this action.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Permission Denied
        '404':
          content:
            application/json:
              examples:
                Unauthorized:
                  value:
                    detail: Not found.
              schema:
                properties:
                  detail:
                    type: string
                type: object
          description: Not found. The API endpoint doesn't exist or resource doesn't
            exist
      summary: verifySelfEmail
      tags:
      - Self
      - Authentication
    parameters:
    - $ref: '#/components/parameters/token'
components:
  parameters:
    token:
      in: path
      name: token
      required: true
      schema:
        type: string
  responses:
    Admin:
      content:
        application/json:
          examples:
            example-1:
              value:
                admin_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                email: user@example.com
                first_name: string
                last_name: string
                privileges:
                - msp_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  msp_name: string
                  name: string
                  org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  org_name: string
                  orggroup_ids:
                  - b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  role: admin
                  scope: org
                  site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  sitegroup_ids:
                  - 6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9
          schema:
            $ref: ./components/schemas/admin.yaml
      description: OK
    OK:
      content:
        application/json:
          schema:
            type: object
      description: OK
