openapi: 3.0.0
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: |
    > *Version 0.2.5*
    >
    > Date: October 22th, 2020
    >

    *This is still a Work In Progress.*

    --- 

    #### Available Postman Envinronments
    * [US Environment](https://documenter.getpostman.com/view/224925/SzYgQufe)
    * [EU Environment](https://documenter.getpostman.com/view/11418445/TVCe28uT)

    ---
    #### Useful links
    * [Mist Homepage](https://www.mist.com)
    * [Mist Documentation](https://www.mist.com/documentation)
    * [Official API Documentation](https://api.mist.com/api/v1/docs/Home) (Mist account required)
    * [Mist Blog](https://www.mist.com/news/?md_post_type=post)
    * [Mist Updates](https://www.mist.com/documentation/category/product-updates/)
  title: Mist Installer API
  version: 0.2.5
servers:
  - description: Mist AWS US
    url: 'https://api.mist.com/api/v1/installer'
  - description: Mist AWS EU
    url: 'https://api.eu.mist.com/api/v1/installer'
  - description: Mist GCP US
    url: 'https://api.gc1.mist.com/api/v1/installer'
paths: 
  '/orgs/{org_id}/alarmtemplates':
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
    
    get:
      description: Get the list of alarm templates
      operationId: getInstallerAlarmTemplates
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    - id: 684dfc5c-fe77-2290-eb1d-ef3d677fe168
                      name: AlarmTemplate 1
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
          description: Successful response
      summary: getInstallerAlarmTemplates
      tags:
        - Alarm Templates
        - Organization
        - Installer
  '/orgs/{org_id}/deviceprofiles':
    get:
      description: Get Device Profiles
      operationId: getInstallerDeviceProfiles_WIP_
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
              examples:
                example-1:
                  value:
                    - id: 6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9
                      name: DeviceProfile 1
          description: Successful response
      summary: getInstallerDeviceProfiles_WIP_
      tags:
        - Devices
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
  '/orgs/{org_id}/devices':
    get:
      description: Get recently claimed devices
      operationId: getInstallerListOfRenctlyClaimedDevices
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - connected
                  properties:
                    map_id:
                      type: string
                      minLength: 1
                    x:
                      type: number
                    y:
                      type: number
                    height:
                      type: number
                    orientation:
                      type: number
                    connected:
                      type: boolean
              examples:
                example-1:
                  value:
                    - mac: 5c5b35000018
                      model: AP41
                      serial: FXLH2015150025
                      connected: true
                    - name: hallway
                      site_name: SJ1
                      deviceprofile_name: SJ1
                      connected: false
                    - map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                      x: 150
                      y: 300
                      height: 2.7
                      orientation: 90
                      connected: true
          description: Successful response
      summary: getInstallerListOfRenctlyClaimedDevices
      tags:
        - Devices
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
    post:
      description: |
        This mirrors `POST /api/v1/orgs/{org_id}/inventory` (see Inventory API)
      operationId: claimInstallerDevices
      parameters:
        - example: application/json
          in: header
          name: Accept
          schema:
            type: string
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
        - example: application/json
          in: header
          name: Content-Type
          schema:
            type: string
      requestBody:
        content:
          application/json:
            examples: {}
            schema:
              description: ''
              items:
                properties:
                  claim-code:
                    type: string
                type: object
              minItems: 1
              type: array
              uniqueItems: true
        description: ''
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: claimInstallerDevices
      tags:
        - Devices
        - Organization
  '/orgs/{org_id}/devices/{device_mac}':
    delete:
      description: Unassign recently claimed devices
      operationId: unassignInstallerRecentlyClaimedDevice
      parameters:
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: unassignInstallerRecentlyClaimedDevice
      tags:
        - Devices
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
      - in: path
        name: device_mac
        required: true
        schema:
          type: string
    put:
      description: 'Provision device '
      operationId: provisionInstallerDevices
      parameters:
        - example: application/json
          in: header
          name: Accept
          schema:
            type: string
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
        - example: application/json
          in: header
          name: Content-Type
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                height:
                  type: number
                map_id:
                  minLength: 1
                  type: string
                name:
                  minLength: 1
                  type: string
                orientation:
                  type: number
                site_id:
                  minLength: 1
                  type: string
                site_name:
                  minLength: 1
                  type: string
                x:
                  type: number
                'y':
                  type: number
                deviceprofile_name:
                  type: string
              required:
                - name
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  detail:
                    type: string
                    minLength: 1
                required:
                  - detail
              examples:
                example-outsite_of_grace_period:
                  value:
                    detail: outside of grace period
      summary: provisionInstallerDevices
      tags:
        - Devices
        - Organization
  '/orgs/{org_id}/devices/{device_mac}/locate':
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
      - in: path
        name: device_mac
        required: true
        schema:
          type: string
    post:
      description: |
        Locate a Device by blinking it’s LED, it’s a persisted state that has to be stopped by calling Stop Locating API
      operationId: startInstallerLocateDevice
      parameters:
        - example: application/json
          in: header
          name: Accept
          schema:
            type: string
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
        - example: application/json
          in: header
          name: Content-Type
          schema:
            type: string
      requestBody:
        content:
          application/json: {}
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: startInstallerLocateDevice
      tags:
        - Devices
        - Organization
  '/orgs/{org_id}/devices/{device_mac}/unlocate':
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
      - in: path
        name: device_mac
        required: true
        schema:
          type: string
    post:
      description: Stop it
      operationId: stopInstallerLocateDevice
      parameters:
        - example: application/json
          in: header
          name: Accept
          schema:
            type: string
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
        - example: application/json
          in: header
          name: Content-Type
          schema:
            type: string
      requestBody:
        content:
          application/json: {}
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: stopInstallerLocateDevice
      tags:
        - Devices
        - Organization
  '/orgs/{org_id}/devices/{device_mac}/{image_name}':
    delete:
      tags:
        - Devices
      operationId: deleteInstallerDeviceImage
      parameters:
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: deleteInstallerDeviceImage
      description: delete image
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
          format: uuid
      - in: path
        name: image_name
        required: true
        schema:
          type: string
      - in: path
        name: device_mac
        required: true
        schema:
          type: string
    post:
      operationId: InstallerDeviceImage
      parameters:
        - example: application/json
          in: header
          name: Accept
          schema:
            type: string
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
        - example: application/json
          in: header
          name: Content-Type
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  format: binary
                  type: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: InstallerDeviceImage
      tags:
        - Devices
        - Organization
      description: Add image
  '/orgs/{org_id}/rftemplates':
    get:
      description: Get RF Template
      operationId: getInstallerRfTemplatesNames
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
              examples:
                example-1:
                  value:
                    - id: bb8a9017-1e36-5d6c-6f2b-551abe8a76a2
                      name: RFTemplate 1
          description: Successful response
      summary: getInstallerRfTemplatesNames
      tags:
        - RF Template
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
  '/orgs/{org_id}/secpolicies':
    get:
      description: Get Secuity Policies
      operationId: getInstallerSecurityPolicies
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
              examples:
                example-1:
                  value:
                    - id: 3bcd0beb-5d0a-4cbd-92c1-14aea91e98ef
                      name: SecuPolicy 1
          description: Successful response
      summary: getInstallerSecurityPolicies
      tags:
        - Security Policies
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
  '/orgs/{org_id}/sitegroups':
    get:
      description: Get Site Groups
      operationId: getInstallerSiteGroups
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
              examples:
                example-1:
                  value:
                    - id: 581328b6-e382-f54e-c9dc-999983183a34
                      name: SiteGroup 1
          description: Successful response
      summary: getInstallerSiteGroups
      tags:
        - Site Groups
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
  '/orgs/{org_id}/sites':
    get:
      description: Get Sites
      operationId: getInstallerSites
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - name
                    - timezone
                    - country_code
                    - latlng
                    - address
                  properties:
                    id:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    timezone:
                      type: string
                      minLength: 1
                    country_code:
                      type: string
                      minLength: 1
                    latlng:
                      type: object
                      properties:
                        lat:
                          type: number
                        lng:
                          type: number
                      required:
                        - lat
                        - lng
                    address:
                      type: string
                      minLength: 1
              examples:
                example-1:
                  value:
                    - id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                      name: Mist Office
                      timezone: America/Los_Angeles
                      country_code: US
                      latlng:
                        lat: 37.295833
                        lng: -122.032946
                      address: '1601 S. Deanza Blvd., Cupertino, CA, 95014'
          description: Successful response
      summary: getInstallerSites
      tags:
        - Sites
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
  '/orgs/{org_id}/sites/{site_name}':
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
      - in: path
        name: site_name
        required: true
        schema:
          type: string
    put:
      description: |
        Often the Installers are asked to assign Devices to Sites. The Sites can either be pre-created or created/modified by the Installer. If this is an update, the same grace period also applies.
      operationId: createOrUpdateInstallerSites
      parameters:
        - example: application/json
          in: header
          name: Accept
          schema:
            type: string
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
        - example: application/json
          in: header
          name: Content-Type
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                timezone:
                  type: string
                  minLength: 1
                country_code:
                  type: string
                  minLength: 1
                latlng:
                  type: object
                  required:
                    - lat
                    - lng
                  properties:
                    lat:
                      type: number
                    lng:
                      type: number
                address:
                  type: string
                  minLength: 1
                rftemplate_name:
                  type: string
                  minLength: 1
                sitegroup_names:
                  type: array
                  items:
                    type: string
              required:
                - timezone
            examples:
              example-1:
                value:
                  timezone: America/Los_Angeles
                  country_code: US
                  latlng:
                    lat: 37.295833
                    lng: -122.032946
                  address: '1601 S. Deanza Blvd., Cupertino, CA, 95014'
                  rftemplate_name: rftemplate1
                  sitegroup_names:
                    - sg1
                    - sg2
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: createOrUpdateInstallerSites
      tags:
        - Sites
        - Organization
  '/orgs/{org_id}/sites/{site_name}/maps':
    get:
      description: Get Maps
      operationId: getInstallerMaps
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: getInstallerMaps
      tags:
        - Maps
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
      - in: path
        name: site_name
        required: true
        schema:
          type: string
  '/orgs/{org_id}/sites/{site_name}/maps/import':
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
      - in: path
        name: site_name
        required: true
        schema:
          type: string
    post:
      description: |-
        Import data from files is a multipart POST which has an file, an optional json, and an optional csv, to create floorplan, assign & place ap if name or mac matches

        #### Body Parameters
        **Parameter**|**Type**|**Description** 
        :-------------: |:-------------: |:-------------: 
        vendor_name|string|Required (ekahau, ibwave)
        import_all_floorplan|boolean|optional (default: false)
        import_height|boolean|optional (default: true)
        import_orientation|boolean|optional (default: true)
      operationId: importInstallerMap
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                vendor_name:
                  type: string
                  minLength: 1
                  enum:
                    - ekahau
                    - ibwave
                import_all_floorplans:
                  type: boolean
                import_height:
                  type: boolean
                import_orientation:
                  type: boolean
              required:
                - vendor_name
            examples:
              example-1:
                value:
                  vendor_name: ekahau
                  import_all_floorplans: true
                  import_height: true
                  import_orientation: false
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                csv:
                  format: binary
                  type: string
        description: ''
      responses:
        '200':
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  site_id:
                    type: string
                    minLength: 1
                  aps:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        mac:
                          type: string
                          minLength: 1
                        action:
                          type: string
                          minLength: 1
                          enum:
                            - placed
                            - assigned-placed
                            - named-placed
                            - assigned-named-placed
                            - ignored
                        map_id:
                          type: string
                          minLength: 1
                        floorplan_id:
                          type: string
                          minLength: 1
                        orientation:
                          type: number
                        height:
                          type: number
                        reason:
                          type: string
                          minLength: 1
                      required:
                        - mac
                        - action
                        - map_id
                        - floorplan_id
                        - orientation
                  floorplans:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                        action:
                          type: string
                          minLength: 1
                        map_id:
                          type: string
                          minLength: 1
                        reason:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - name
                        - action
                        - map_id
                  summary:
                    type: object
                    required:
                      - num_ap_assigned
                      - num_map_assigned
                      - num_inv_assigned
                    properties:
                      num_ap_assigned:
                        type: number
                      num_map_assigned:
                        type: number
                      num_inv_assigned:
                        type: number
                required:
                  - site_id
                  - aps
                  - floorplans
                  - summary
              examples:
                example-placed:
                  value:
                    site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                    aps:
                      - mac: 5c5b35000001
                        action: placed
                        map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                        floorplan_id: cbdb7f0b-3be0-4872-88f9-58790b509c23-j68kows8
                        orientation: 45
                        height: 3
                    floorplans:
                      - id: cbdb7f0b-3be0-4872-88f9-58790b509c23-j68kows8
                        name: map1
                        action: imported
                        map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                    summary:
                      num_ap_assigned: 1
                      num_map_assigned: 1
                      num_inv_assigned: 1
                example-assigned_and_placed:
                  value:
                    site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                    aps:
                      - mac: 5c5b35000001
                        map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                        action: assigned-placed
                        floorplan_id: cbdb7f0b-3be0-4872-88f9-58790b509c23-j68kows8
                        orientation: 45
                        height: 3
                    floorplans:
                      - id: cbdb7f0b-3be0-4872-88f9-58790b509c23-j68kows8
                        name: map1
                        action: imported
                        map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                    summary:
                      num_ap_assigned: 1
                      num_map_assigned: 1
                      num_inv_assigned: 1
                example-assigned_named_and_placed:
                  value:
                    site_id: 4ac1dcf4-9d8b-7211-65c4-057819f0862b
                    aps:
                      - mac: 5c5b35000001
                        map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                        action: assigned-named-placed
                        floorplan_id: cbdb7f0b-3be0-4872-88f9-58790b509c23-j68kows8
                        orientation: 45
                    floorplans:
                      - id: cbdb7f0b-3be0-4872-88f9-58790b509c23-j68kows8
                        name: map1
                        action: imported
                        map_id: 845a23bf-bed9-e43c-4c86-6fa474be7ae5
                    summary:
                      num_ap_assigned: 1
                      num_map_assigned: 1
                      num_inv_assigned: 1
          description: Successful response
      summary: importInstallerMap
      tags:
        - Maps
        - Organization
  '/orgs/{org_id}/sites/{site_name}/maps/{map_id}':
    delete:
      description: Delete Map
      operationId: deleteInstallerMap
      parameters:
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: deleteInstallerMap
      tags:
        - Maps
        - Organization
    parameters:
      - in: path
        name: org_id
        required: true
        schema:
          type: string
      - in: path
        name: site_name
        required: true
        schema:
          type: string
      - schema:
          type: string
        name: map_id
        in: path
        required: true
    post:
      description: "Create a MAP\r\n #### Body Parameters \r\n**Parameter**|**Type**|**Description** \r\n :-------------: |:-------------: |:-------------: \r\nname|string|The name of the map\r\ntype|string|\"image / google, default is image\"\r\nppm|float|\"when type=image, pixels per meter\"\r\nwidth|int|\"when type=image, width of the image map\"\r\nheight|int|\"when type=image, height of the image map\"\r\nurl|string|\"when type=image, the url\"\r\nthumbnail_url|string|\"when type=image, the url for the thumbnail image / preview\"\r\nview|string|when type=google. roadmap / satellite / hybrid / terrain\r\norigin_x|int|\"the user-annotated x origin, pixels\"\r\norigin_y|int|\"the user-annotated y origin, pixels\"\r\norientation|int|\"orientation of the map, 0 means up is north, 90 means up is west. default is 0\"\r\nlatlng_tl|latlng|\"when type=google, latitude / longitude of the top-left corner\"\r\nlatlng_br|latlng|\"when type=google, latitude / longitude of the bottom-right corner\"\r\nwayfinding|object|properties related to wayfinding\r\nwayfinding_path|object|a JSON blob for wayfinding (using Dijkstra's algorithm)\r\nwall\\_path|object|a JSON blob for wall definition (same format as wayfinding_path)\r\nsitesurvey\\_path|list|a list of JSON blob for site survey path (same format as wayfinding_path)\r\nlocked|boolean|whether this map is considered locked down\r\nflags|list|name/val pair objects for location engine to use\r\n"
      operationId: createInstallerMap
      parameters:
        - example: application/json
          in: header
          name: Accept
          schema:
            type: string
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
        - example: application/json
          in: header
          name: Content-Type
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/map.v1.yaml
            examples:
              example-1:
                value:
                  name: string
                  type: string
                  ppm: 0
                  width: 0
                  height: 0
                  origin_x: 0
                  origin_y: 0
                  orientation: 0
                  locked: true
                  wayfinding:
                    snap_to_path: true
                    micello:
                      account_key: string
                      map_id: string
                      default_level_id: 0
                  wayfinding_path:
                    coordinate: string
                    nodes:
                      - name: string
                        position:
                          x: 0
                          'y': 0
                        edges:
                          N2: string
                  wall_path:
                    coordinate: string
                    nodes:
                      - name: string
                        position:
                          x: 0
                          'y': 0
                        edges:
                          N2: string
                  sitesurvey_path:
                    - coordinate: string
                      nodes:
                        - name: string
                          position:
                            x: 0
                            'y': 0
                          edges:
                            N2: string
                      name: string
                      id: string
                  flags: {}
                  url: string
                  thumbnail_url: string
                  view: string
                  latlng_tl:
                    lat: string
                    lnt: string
                  latlng_bt:
                    lat: string
                    lnt: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: createInstallerMap
      tags:
        - Maps
        - Organization
    put:
      description: Update map
      operationId: updateInstallerMap
      parameters:
        - example: application/json
          in: header
          name: Accept
          schema:
            type: string
        - example: '{{csrftoken}}'
          in: header
          name: X-CSRFToken
          schema:
            type: string
        - example: application/json
          in: header
          name: Content-Type
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/map.v1.yaml
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: updateInstallerMap
      tags:
        - Maps
        - Organization
  '/sites/{site_name}/optimize':
    get:
      description: "After installation is considered complete (APs are placed on maps, all powered up), you can trigger an optimize operation where RRM will kick in (and maybe other things in the future) before it’s automatically scheduled.\r\n\r\n"
      operationId: optimizeInstallerRrm
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: optimizeInstallerRrm
      tags:
        - RRM
    parameters:
      - in: path
        name: site_name
        required: true
        schema:
          type: string
  
components:
  schemas: {}
